### ISSUE TITLE
Examples for the RecSys 2021 tutorial on End-2-End Session-based recommendation

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Transformers4Rec#16]
- [ ] Preproc with NVTabular
- [ ] Training with Transformers4Rec
- [ ] Inference with Triton

**Comment by Ahanmr** [comment]
Hi, I'm getting the following error during the example notebook.

`dataset = nvt.Dataset(interactions_merged_df)`

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_10047/1382503116.py in <module>
----> 1 nvt.Dataset(interactions_merged_df)

/opt/conda/lib/python3.7/site-packages/nvtabular/io/dataset.py in __init__(self, path_or_source, engine, npartitions, part_size, part_mem_fraction, storage_options, dtypes, client, cpu, base_dataset, schema, **kwargs)
    318                     )
    319                 else:
--> 320                     raise ValueError("Only parquet, csv, and avro supported (for now).")
    321             else:
    322                 self.engine = engine(

ValueError: Only parquet, csv, and avro supported (for now)
```

**Comment by rnyak** [comment]
@Ahanmr hello.  Are you using a container? if yes which docker container? If not, please provide details about your env...

To be able to run the end-to-end notebook, you need two containers:

`merlin-pytorch-training:21.12`  container to run the entire notebook. First pull the container and launch it. Then, in the container you can git clone the `Transformers4rec` and then do
```
cd Transformers4Rec
git checkout main
git pull origin main
pip install -e .
```
Then  launch the jupyter lab and run the notebooks for ETL and training.

For the inference part of the notebook, you need merlin-inference container only to serve/load the models to Triton inference server. In order to do that please follow the explanations in the notebook:
# Launch the docker container

```
docker run -it --gpus device=0 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v <path_to_saved_models>:/workspace/models/ nvcr.io/nvidia/merlin/merlin-inference:21.12
```
This script will mount your local model-repository folder that includes your saved models from the previous cell to /workspace/models directory in the merlin-inference docker container.

# Start triton server
After you started the merlin-inference container, you can start triton server with the command below. You need to provide correct path of the models folder.

tritonserver --model-repository=<path_to_models> --model-control-mode=explicit

Note: The model-repository path for our example is /workspace/models. The models haven't been loaded, yet. Below, we will request the Triton server to load the saved ensemble model below.

**Comment by Ahanmr** [comment]
`from transformers4rec.torch.utils.examples_utils import fit_and_evaluate`
`OT_results = fit_and_evaluate(recsys_trainer, start_time_index=7, end_time_index=8, input_dir='./preproc_sessions_by_day')`

I'm trying to run this snippet in the notebook but I'm getting this error, I believe that something here isn't accessible to the model.fit(), any idea why this might be happening?
```
***** Launch training for day 7: *****
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_25823/251429872.py in <module>
      1 from transformers4rec.torch.utils.examples_utils import fit_and_evaluate
----> 2 OT_results = fit_and_evaluate(recsys_trainer, start_time_index=7, end_time_index=8, input_dir='./preproc_sessions_by_day')

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/examples_utils.py in fit_and_evaluate(trainer, start_time_index, end_time_index, input_dir)
     75         trainer.train_dataset_or_path = train_paths
     76         trainer.reset_lr_scheduler()
---> 77         trainer.train()
     78 
     79         # 3. Evaluate on valid data of time_index+1

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1113 
   1114         # Data loader and number of training steps
-> 1115         train_dataloader = self.get_train_dataloader()
   1116 
   1117         # Setting up training control variables:

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/trainer.py in get_train_dataloader(self)
    148             drop_last=self.args.dataloader_drop_last,
    149             shuffle=True,
--> 150             shuffle_buffer_size=self.args.shuffle_buffer_size,
    151         )
    152 

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in from_schema(cls, schema, paths_or_dataset, batch_size, max_sequence_length, continuous_features, categorical_features, targets, collate_fn, shuffle, buffer_size, parts_per_chunk, separate_labels, named_labels, sparse_names, sparse_max, **kwargs)
    323                 sparse_max=sparse_max,
    324                 schema=schema,
--> 325                 **kwargs,
    326             )
    327 

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in __init__(self, paths_or_dataset, batch_size, max_sequence_length, conts, cats, labels, collate_fn, engine, buffer_size, reader_kwargs, shuffle, seed_fn, parts_per_chunk, device, global_size, global_rank, sparse_names, sparse_max, sparse_as_dense, drop_last, schema, **kwargs)
    225             self.drop_last = drop_last
    226 
--> 227             self.set_dataset(buffer_size, engine, reader_kwargs)
    228 
    229             loader = DataLoader(

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in set_dataset(self, buffer_size, engine, reader_kwargs)
    261                 buffer_size,
    262                 engine,
--> 263                 reader_kwargs,
    264             )
    265             self.dataset = dataset

~/Transformers4Rec/examples/end-to-end-session-based/merlin_standard_lib/utils/misc_utils.py in validate_dataset(paths_or_dataset, batch_size, buffer_size, engine, reader_kwargs)
    237     else:
    238         reader_kwargs["part_mem_fraction"] = buffer_size
--> 239     return Dataset(files, engine=engine, **reader_kwargs)

/opt/conda/lib/python3.7/site-packages/nvtabular/io/dataset.py in __init__(self, path_or_source, engine, npartitions, part_size, part_mem_fraction, storage_options, dtypes, client, cpu, base_dataset, schema, **kwargs)
    300                 if engine == "parquet":
    301                     self.engine = ParquetDatasetEngine(
--> 302                         paths, part_size, storage_options=storage_options, cpu=self.cpu, **kwargs
    303                     )
    304                 elif engine == "csv":

/opt/conda/lib/python3.7/site-packages/nvtabular/io/parquet.py in __init__(self, paths, part_size, storage_options, row_groups_per_part, legacy, batch_size, cpu, **kwargs)
    279         if row_groups_per_part is None:
    280             self._real_meta, rg_byte_size_0 = run_on_worker(
--> 281                 _sample_row_group, self._path0, self.fs, cpu=self.cpu, memory_usage=True
    282             )
    283             row_groups_per_part = self.part_size / rg_byte_size_0

/opt/conda/lib/python3.7/site-packages/nvtabular/utils.py in run_on_worker(func, *args, **kwargs)
    178         return dask.delayed(func)(*args, **kwargs).compute()
    179     # No Dask client - Use simple function call
--> 180     return func(*args, **kwargs)

/opt/conda/lib/python3.7/site-packages/nvtabular/io/parquet.py in _sample_row_group(path, fs, cpu, n, memory_usage)
   1170             _df = pq.ParquetFile(f0).read_row_group(0).to_pandas()
   1171     else:
-> 1172         if cudf.utils.ioutils._is_local_filesystem(fs):
   1173             # Allow cudf to open the file if this is a local file
   1174             # system (can be significantly faster in this case)

AttributeError: 'NoneType' object has no attribute 'utils'
```

**Comment by Ahanmr** [comment]
Also is there an automated way to generate `schema.pb` for my dataset?

**Comment by rnyak** [comment]
> `from transformers4rec.torch.utils.examples_utils import fit_and_evaluate` `OT_results = fit_and_evaluate(recsys_trainer, start_time_index=7, end_time_index=8, input_dir='./preproc_sessions_by_day')`
> 
> I'm trying to run this snippet in the notebook but I'm getting this error, I believe that something here isn't accessible to the model.fit(), any idea why this might be happening?
> 
> ```
> ***** Launch training for day 7: *****
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /tmp/ipykernel_25823/251429872.py in <module>
>       1 from transformers4rec.torch.utils.examples_utils import fit_and_evaluate
> ----> 2 OT_results = fit_and_evaluate(recsys_trainer, start_time_index=7, end_time_index=8, input_dir='./preproc_sessions_by_day')
> 
> /opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/examples_utils.py in fit_and_evaluate(trainer, start_time_index, end_time_index, input_dir)
>      75         trainer.train_dataset_or_path = train_paths
>      76         trainer.reset_lr_scheduler()
> ---> 77         trainer.train()
>      78 
>      79         # 3. Evaluate on valid data of time_index+1
> 
> /opt/conda/lib/python3.7/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
>    1113 
>    1114         # Data loader and number of training steps
> -> 1115         train_dataloader = self.get_train_dataloader()
>    1116 
>    1117         # Setting up training control variables:
> 
> /opt/conda/lib/python3.7/site-packages/transformers4rec/torch/trainer.py in get_train_dataloader(self)
>     148             drop_last=self.args.dataloader_drop_last,
>     149             shuffle=True,
> --> 150             shuffle_buffer_size=self.args.shuffle_buffer_size,
>     151         )
>     152 
> 
> /opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in from_schema(cls, schema, paths_or_dataset, batch_size, max_sequence_length, continuous_features, categorical_features, targets, collate_fn, shuffle, buffer_size, parts_per_chunk, separate_labels, named_labels, sparse_names, sparse_max, **kwargs)
>     323                 sparse_max=sparse_max,
>     324                 schema=schema,
> --> 325                 **kwargs,
>     326             )
>     327 
> 
> /opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in __init__(self, paths_or_dataset, batch_size, max_sequence_length, conts, cats, labels, collate_fn, engine, buffer_size, reader_kwargs, shuffle, seed_fn, parts_per_chunk, device, global_size, global_rank, sparse_names, sparse_max, sparse_as_dense, drop_last, schema, **kwargs)
>     225             self.drop_last = drop_last
>     226 
> --> 227             self.set_dataset(buffer_size, engine, reader_kwargs)
>     228 
>     229             loader = DataLoader(
> 
> /opt/conda/lib/python3.7/site-packages/transformers4rec/torch/utils/data_utils.py in set_dataset(self, buffer_size, engine, reader_kwargs)
>     261                 buffer_size,
>     262                 engine,
> --> 263                 reader_kwargs,
>     264             )
>     265             self.dataset = dataset
> 
> ~/Transformers4Rec/examples/end-to-end-session-based/merlin_standard_lib/utils/misc_utils.py in validate_dataset(paths_or_dataset, batch_size, buffer_size, engine, reader_kwargs)
>     237     else:
>     238         reader_kwargs["part_mem_fraction"] = buffer_size
> --> 239     return Dataset(files, engine=engine, **reader_kwargs)
> 
> /opt/conda/lib/python3.7/site-packages/nvtabular/io/dataset.py in __init__(self, path_or_source, engine, npartitions, part_size, part_mem_fraction, storage_options, dtypes, client, cpu, base_dataset, schema, **kwargs)
>     300                 if engine == "parquet":
>     301                     self.engine = ParquetDatasetEngine(
> --> 302                         paths, part_size, storage_options=storage_options, cpu=self.cpu, **kwargs
>     303                     )
>     304                 elif engine == "csv":
> 
> /opt/conda/lib/python3.7/site-packages/nvtabular/io/parquet.py in __init__(self, paths, part_size, storage_options, row_groups_per_part, legacy, batch_size, cpu, **kwargs)
>     279         if row_groups_per_part is None:
>     280             self._real_meta, rg_byte_size_0 = run_on_worker(
> --> 281                 _sample_row_group, self._path0, self.fs, cpu=self.cpu, memory_usage=True
>     282             )
>     283             row_groups_per_part = self.part_size / rg_byte_size_0
> 
> /opt/conda/lib/python3.7/site-packages/nvtabular/utils.py in run_on_worker(func, *args, **kwargs)
>     178         return dask.delayed(func)(*args, **kwargs).compute()
>     179     # No Dask client - Use simple function call
> --> 180     return func(*args, **kwargs)
> 
> /opt/conda/lib/python3.7/site-packages/nvtabular/io/parquet.py in _sample_row_group(path, fs, cpu, n, memory_usage)
>    1170             _df = pq.ParquetFile(f0).read_row_group(0).to_pandas()
>    1171     else:
> -> 1172         if cudf.utils.ioutils._is_local_filesystem(fs):
>    1173             # Allow cudf to open the file if this is a local file
>    1174             # system (can be significantly faster in this case)
> 
> AttributeError: 'NoneType' object has no attribute 'utils'
> ```

@Ahanmr I will look into that. Did you check if your data is in the `input_dir='./preproc_sessions_by_day'` path? Do you see folders for each day under the `/preproc_sessions_by_day'` and parquet files in each one?  If not that means you did not preprocess the dataset properly? Which notebook are you running btw? 

Also please open another issue because I am going to close this one, since this task is completed.

**Comment by rnyak** [comment]
> Also is there an automated way to generate `schema.pb` for my dataset?

Yes with NVTabular you can do it.

**Comment by rnyak** [comment]
Closing since this task was completed.
