### ISSUE TITLE
Rename the top-N metrics names suffix

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/Transformers4Rec#187]
Just a minor remark. Could the top-N metrics names suffix be something like `ndcg@10` rather than `ndcgat_10`?
If you agree, we could maybe do this in another PR

_Originally posted by @gabrielspmoreira in https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/143#discussion_r702140922_

**Comment by rnyak** [comment]
@sararb can we close this?

**Comment by sararb** [comment]
You're right!
