### ISSUE TITLE
PyTorch installation errors [BUG]

### ISSUE THREAD

**Issue by pintonos** [NVIDIA-Merlin/Transformers4Rec#257]
### Bug description
I did an install of the PyTorch version of Transformers4Rec and tried to run the example code in the ReadMe. However, the needed `torchmetrics` library was not automatically installed and needed to be installed by hand.
After installing torchmetrics manually following error appeared:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-77b1c0b67bb1> in <module>()
----> 1 from transformers4rec import torch as tr
      2 
      3 schema: tr.Schema = tr.data.tabular_sequence_testing_data.schema
      4 # Or read schema from disk: tr.Schema().from_json(SCHEMA_PATH)
      5 max_sequence_length, d_model = 20, 64

8 frames
/usr/lib/python3.7/importlib/util.py in find_spec(name, package)
    112         else:
    113             if spec is None:
--> 114                 raise ValueError('{}.__spec__ is None'.format(name))
    115             return spec
    116 

ValueError: transformers.__spec__ is None
```

### Steps/Code to reproduce bug

1. Install PyTorch version.
2. Try the example code.

### Expected behavior
Automatic installation of depenencies.

### Environment details
- Transformers4Rec version: 0.1.1
- Platform: Google Colab
- Python version: 3.7.12
- Huggingface Transformers version: 4.9.2
- PyTorch version (GPU?): 1.9.0+cu102
- Tensorflow version (GPU?): 2.6.0

**Comment by rnyak** [comment]
@pintonos thanks for reporting this. Please do `pip install torchmetrics==0.3.2`. This will fix the error. If you are using our `nvcr.io/nvidia/merlin/merlin-pytorch-training:21.09` docker images, torchmetrics should be installed automatically. Feel free to respond if you still have issues/questions.

**Comment by marcromeyn** [comment]
We should make this clearer in our docs. In order to install all dependencies for the PyTorch part of the API you can run: pip install "transformers4rec[pytorch]"

**Comment by rnyak** [comment]
> We should make this clearer in our docs. In order to install all dependencies for the PyTorch part of the API you can run: pip install "transformers4rec[pytorch]"

@marcromeyn we already have `pip install transformers4rec[torch,nvtabular]` in the docs. You suggest to add more explanation around that?

**Comment by pintonos** [comment]
It seems there is a difference between `transformers4rec[torch,nvtabular]` and `transformers4rec[pytorch,nvtabular]`. Latter is working fine.

**Comment by rnyak** [comment]
@pintonos thanks! we will fix the README.

**Comment by benfred** [comment]
@rnyak fixed the README to have the correct torch install instructions in #260 - closing
