### ISSUE TITLE
[BUG] getting started nb gives error with PyT 1.10.0

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#305]
### Bug description

The getting-started-session-based [training nb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb) gives the following error with PyT 1.10.0 version in the training loop:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1148/2595200145.py in <module>
     16     trainer.train_dataset_or_path = train_paths
     17     trainer.reset_lr_scheduler()
---> 18     trainer.train()
     19     trainer.state.global_step +=1
     20     print('finished')

/opt/conda/lib/python3.8/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1314                         tr_loss_step = self.training_step(model, inputs)
   1315                 else:
-> 1316                     tr_loss_step = self.training_step(model, inputs)
   1317 
   1318                 if (

/opt/conda/lib/python3.8/site-packages/transformers/trainer.py in training_step(self, model, inputs)
   1865             loss = self.deepspeed.backward(loss)
   1866         else:
-> 1867             loss.backward()
   1868 
   1869         return loss.detach()

/opt/conda/lib/python3.8/site-packages/torch/_tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    305                 create_graph=create_graph,
    306                 inputs=inputs)
--> 307         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    308 
    309     def register_hook(self, hook):

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    152         retain_graph = create_graph
    153 
--> 154     Variable._execution_engine.run_backward(
    155         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    156         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: unique_by_key: failed on 2nd step: cudaErrorInvalidValue: invalid argument
```

### Expected behavior
Example notebooks should run without errors.

### Environment details
- Transformers4Rec version: v0.1.1
- Platform: Docker image - nvcr.io/nvstaging/merlin/tmp-merlin-pytorch-training:nightly 
- Python version: 3.8.12
- Huggingface Transformers version: 4.12.2
- PyTorch version (GPU?): 1.10.0
- Tensorflow version (GPU?): NA

### Additional context
To repro the error, it is required to upgrade Transformers version to 4.12.2 to be able to run with PyT 1.10.0.

**Comment by rnyak** [comment]
This error occurs only with optimized PyT version in the DLFW container,  and does not pop up with public PyT 1.10.0.

**Comment by rnyak** [comment]
Closing  this since this error occurs only with optimized PyT version in the DLFW container, and does not pop up with public PyT 1.10.0.

**Comment by arunslb123** [comment]
![image](https://user-images.githubusercontent.com/3520124/140442065-1c44e831-b177-4470-b747-874543475081.png)

I'm getting the same error in public PyT 1.10.0
