### ISSUE TITLE
[QST] How to run a getting started notebooks on GPU using conda environment?

### ISSUE THREAD

**Issue by arunslb123** [NVIDIA-Merlin/Transformers4Rec#314]
# ❓ Questions & Help

## Details

I created a conda environment for NVTabular using its instructions, then installed NVTabular, Transformers4rec from source (git+pip). After that I installed pytorch 1.10 cu11 GPU and tried running [end-end examples](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based), and currently getting the following error.

![image](https://user-images.githubusercontent.com/3520124/140509660-7dfa40ae-36a6-4416-807a-69bf57d84fa1.png)

Is there any conda installation scripts that I can follow to run the above notebooks successfully?

**Comment by marcromeyn** [comment]
Thanks for reporting this! Could you share the full stacktrace of the error you're getting?

**Comment by arunslb123** [comment]
![image](https://user-images.githubusercontent.com/3520124/140590788-91918c9d-b273-4bb2-94de-bf652519c9f3.png) Here's the full stacktrace of the error message.

**Comment by arunslb123** [comment]
this is how I did my setups 

    1  conda env create -f=env.yml   ( nvtabular 11.2 env [file](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/conda/environments/nvtabular_dev_cuda11.2.yml) )
    2  conda activate nvtabular_dev_11.2
    3  pip install ipykernel
    4  python -m ipykernel install --user --name=nvt
    5  git pull https://github.com/NVIDIA-Merlin/NVTabular.git
    6  git clone https://github.com/NVIDIA-Merlin/NVTabular.git
    7  cd NVTabular/
    8  ls
    9  pip install -e .
   10  cd ..
   11  git clone https://github.com/NVIDIA-Merlin/Transformers4Rec.git
   12  cd Transformers4Rec/
   13  pip install -e .
   14  pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
   15  pip install torchmetrics==0.3.2
   16  cd ..
   17  history hist.txt
   18  history > hist.txt

**Comment by rnyak** [comment]
@arunslb123 Can you please downgrade PyTorch to 1.9.0  and test again? If you face the error again please let us know. In the mean time we will look into PyTorch 1.10.0 error that you get.

What's your cuda version? 11.2 or 11.3?  Can you post here `nvidia-smi` and `nvcc --version` print outs. Thanks.

**Comment by arunslb123** [comment]
After updating it to pyt 1.9.0, I'm getting another keyerror. Any hint for this error @rnyak ?
![image](https://user-images.githubusercontent.com/3520124/140676913-e395b37e-8868-4fc4-8431-42ddc65fccb5.png)

Details on GPU and library versions:

![image](https://user-images.githubusercontent.com/3520124/140677050-d4113516-ea4b-4070-937b-44d80ca37505.png)

**Comment by arunslb123** [comment]
@rnyak , I tried so many things, and finally managed to get it work after updating my pytorch to pytorch nightly pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

**Comment by rnyak** [comment]
> this is how I did my setups
> 
> ```
> 1  conda env create -f=env.yml   ([env.yml ](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/conda/environments/nvtabular_dev_cuda11.2.yml))
> 2  conda activate nvtabular_dev_11.2
> 3  pip install ipykernel
> 4  python -m ipykernel install --user --name=nvt
> 6  git clone https://github.com/NVIDIA-Merlin/NVTabular.git
> 7  cd NVTabular/
> 8  ls
> 9  pip install -e .
> ```
> 
> 10 cd .. 11 git clone https://github.com/NVIDIA-Merlin/Transformers4Rec.git 12 cd Transformers4Rec/ 13 pip install -e . 14 pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html 15 pip install torchmetrics==0.3.2 16 cd .. 18 history > hist.txt

@arunslb123 is there a reason you installed torch for cuda 11.3 in step 14? your cuda version is 11.2 and cuda toolkit is 11.0. 

> this is how I did my setups
> 
> ```
> 1  conda env create -f=env.yml   ([env.yml ](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/conda/environments/nvtabular_dev_cuda11.2.yml))
> 2  conda activate nvtabular_dev_11.2
> 3  pip install ipykernel
> 4  python -m ipykernel install --user --name=nvt
> 6  git clone https://github.com/NVIDIA-Merlin/NVTabular.git
> 7  cd NVTabular/
> 8  ls
> 9  pip install -e .
> ```
> 
> 10 cd .. 11 git clone https://github.com/NVIDIA-Merlin/Transformers4Rec.git 12 cd Transformers4Rec/ 13 pip install -e . 14 pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html 15 pip install torchmetrics==0.3.2 16 cd .. 18 history > hist.txt

@arunslb123 is there a reason you installed torch for cuda 11.3 in step 14? your cuda version is 11.2 and cuda toolkit version is 11.0.

**Comment by arunslb123** [comment]
@rnyak , no reasons, maybe that's a mistake and I will create another env with cuda 11.2 and see how it goes. Meanwhile, I fixed the above two bugs (key errors) by using pytorch nightly.
