### ISSUE TITLE
[QST] Install NVTabular on Databricks

### ISSUE THREAD

**Issue by vanessamarinho** [NVIDIA-Merlin/Transformers4Rec#323]
# ❓ Questions & Help

## Details

Hello, the library seems really great and we are looking forward to try it :) !

We wanted to install `nvtabular` on a Databricks notebook. However, when we do `%pip install nvtabular` the installation fails with the error `protoc not found`. (Note: we even tried an user's answer listed [here](https://github.com/NVIDIA-Merlin/NVTabular/issues/1044) `--no-binary=nvtabular` and still got the same error). We are not able to install protoc/protobuf on the Databricks cluster. As this is the suggested library, we wonder if there is another way to install it on Databricks without `apt-get` or `conda` commands?

Many thanks!!

**Comment by rnyak** [comment]
@vanessamarinho thanks for your question. Could you please give details about why you cannot use docker on databricks? we have a solution with [that](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/docs/source/resources/cloud_integration.md#databricks).

**Comment by rnyak** [comment]
@benfred for viz.

**Comment by vanessamarinho** [comment]
Hi @rnyak , this is because we can only use the interactive clusters via notebooks. We can still choose which libraries to install via terraform, but not much more than that.

**Comment by rnyak** [comment]
@vanessamarinho thanks for the clarification. There was another issue reported on installing NVTabular via `pip install ..` command. Please see the solution there:  https://github.com/NVIDIA-Merlin/NVTabular/issues/1044

`You'll need the protoc compiler installed first: http://google.github.io/proto-lens/installing-protoc.html` Let us know if that'd solve the issue.

Please note that, NVTabular installation via  `pip install nvtabular` without Rapids cuDF will mean running nvtabular only on the CPU, and remove gpu support.   That means you cannot use `data_loader_engine='nvtabular'` arg, instead you need to use `data_loader_engine='pyarrow'` (for CPU, dont forget to add `no_cuda=True` as well).

Let us know how it goes.

**Comment by vanessamarinho** [comment]
Hi @rnyak, thanks for your answer!

We were able to install nvtabular from the specific commit mentioned in that issue `pip install nvtabular@git+git://github.com/NVIDIA/NVTabular@25e975df67a78f44cd53ad7d8bbd9565b44cdaeb`, so we will try to see how far we can go with this version.

Regarding the flag `--no-binary=nvtabular`, we were not able to install with it because it still requires protoc when building the wheel. Unfortunately, we are not able to install protoc on our clusters, it requires sudo/apt-get commands that we are not allowed to use there :(

We will proceed the exploration with that older version and also do as you suggested and use Transformers4rec with the pyarrow data loader (no NVTabular).

Many thanks for your help!
