### ISSUE TITLE
[QST] anyone got success using custom container on vertex ai?

### ISSUE THREAD

**Issue by arunslb123** [NVIDIA-Merlin/Transformers4Rec#339]
# ❓ Questions & Help

## Details

I tried running creating a custom container on vertex ai to run my T4R notebooks

My dockerfile is as follows

FROM nvcr.io/nvidia/merlin/merlin-inference:21.11
EXPOSE 8080
EXPOSE 8888
ENTRYPOINT jupyter lab --ip 0.0.0.0 --port 8080 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''

I am getting jupyter status unhealthy error and couldn't run the notebooks. Has anyone got any success creating a custom container to run T4R library notebooks? Any hint, help much appreciated :)

**Comment by rnyak** [comment]
@arunslb123 thanks for your question. I am not familiar with Vertex AI. Hopefully someone who is familiar with it will respond here. But to clarify, why are you trying to launch TF4Rec notebooks with `merlin-inference:21.11` container? You cannot run TF4Rec training notebooks on `merlin-inference` container. You need `nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11` container instead. Merlin inference is only to launch the Triton Inference Server and load/serve the saved models.

**Comment by arunslb123** [comment]
Thanks @rnyak , will try that. My current pain point is I cannot run nvtabular.triton inference from the current end-end notebooks, I just pip installed as pip install tritonclient[all] So thought of using docker inference container to run it on vertex ai.

![image](https://user-images.githubusercontent.com/3520124/144146781-2b2acf8f-d42f-48d4-8b5c-f29c2c7eb627.png)

Also do you have any documentations on how you created jupyter lab on your nvidia courses? Everything works well in that course. If there's any conda yaml files, I will reproduce the same to run my notebooks.

**Comment by rnyak** [comment]
@arunslb123 sorry that your are having issues. Let me write down the steps for executing the end-to-end nb:

You need two containers:
1.  `merlin-pytorch-training:21.11` container to run the entire notebook. 

in this container you can git clone the Transformers4rec and then do
```
cd Transformers4Rec
git checkout main
git pull origin main
pip install -e .
```

2.  For the inference part of the notebook, you need `merlin-inference` container only to serve/load the models to Triton inference server. In order to do that please follow the explanations in the notebook:

```
# Launch the docker container

docker run -it --gpus device=0 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v <path_to_saved_models>:/workspace/models/ nvcr.io/nvidia/merlin/merlin-inference:21.11

This script will mount your local model-repository folder that includes your saved models from the previous cell to /workspace/models directory in the merlin-inference docker container.

# Start triton server
After you started the merlin-inference container, you can start triton server with the command below. You need to provide correct path of the models folder.

tritonserver --model-repository=<path_to_models> --model-control-mode=explicit

Note: The model-repository path for our example is /workspace/models. The models haven't been loaded, yet. Below, we will request the Triton server to load the saved ensemble model below.
```
For the error you get, can you please try to run the command below in your  `merlin-pytorch-training:21.11` docker container terminal before launching the jupyter notebook:

`export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='python'`

Let us know if that solves the issue :)

**Comment by rnyak** [comment]
@arunslb123 as a side info we have some instructions for running our notebooks on cloud (hope that'd help also). Please visit:

https://nvidia-merlin.github.io/NVTabular/main/resources/cloud_integration.html

but you'd still need the inference container launched there as well, and load the trained and saved models (generated from `export_pytorch_ensemble()`) to the Triton IS and then send request from client notebook (training notebook).

**Comment by arunslb123** [comment]
@rnyak , I followed all the above steps and currently getting this issue. Any pointers on this? Thanks

![image](https://user-images.githubusercontent.com/3520124/144770077-7717fdd2-d271-434e-98e0-b6e91012a050.png)

**Comment by rnyak** [comment]
> @rnyak , I followed all the above steps and currently getting this issue. Any pointers on this? Thanks
> 
> ![image](https://user-images.githubusercontent.com/3520124/144770077-7717fdd2-d271-434e-98e0-b6e91012a050.png)
> 
> The above error message happened when I was running the below code.
> 
> ![image](https://user-images.githubusercontent.com/3520124/144770438-a7b5dbb9-c859-49de-b812-d622f8b0a60c.png)

Can you please share your script of  launching the inference container? Also please share the tree structure of your models folder? (model repository folder  that triton reads the configs basically)..

**Comment by arunslb123** [comment]
@rnyak , My tree structure 

![image](https://user-images.githubusercontent.com/3520124/144938013-7a9397fd-941a-423f-852d-8140aee85b1a.png)

script I am using to launch the inference container:

docker run -it --gpus device=0 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/jupyter/Transformers4Rec/examples/end-to-end-session-based/models:/workspace/models nvcr.io/nvidia/merlin/merlin-inference:21.11

tritonserver --model-repository=/workspace/models --model-control-mode=explicit

Error message:

![image](https://user-images.githubusercontent.com/3520124/144938367-2a49864e-d9f2-424b-b470-a84b5a7f9049.png)

**Comment by arunslb123** [comment]
Also, this is the error I am getting inside the docker server.

![image](https://user-images.githubusercontent.com/3520124/144945485-33de8a0d-c8d5-4538-8d7d-009abae3632b.png)

**Comment by rnyak** [comment]
> Also, this is the error I am getting inside the docker server. "No module named " nvtabular.inference.workflow"
> 
> ![image](https://user-images.githubusercontent.com/3520124/144945485-33de8a0d-c8d5-4538-8d7d-009abae3632b.png)

can you please go to `nvtabular` directory and then do `git checkout main` && `git pull origin main` && `pip install -e .` to pull the latest changes in the NVTabular both in your training and inference containers.  Let us know if this solves your issue.

**Comment by rnyak** [comment]
> @rnyak , My tree structure
> 
> ![image](https://user-images.githubusercontent.com/3520124/144938013-7a9397fd-941a-423f-852d-8140aee85b1a.png)
> 
> script I am using to launch the inference container:
> 
> docker run -it --gpus device=0 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/jupyter/Transformers4Rec/examples/end-to-end-session-based/models:/workspace/models nvcr.io/nvidia/merlin/merlin-inference:21.11
> 
> tritonserver --model-repository=/workspace/models --model-control-mode=explicit
> 
> Error message:
> 
> ![image](https://user-images.githubusercontent.com/3520124/144938367-2a49864e-d9f2-424b-b470-a84b5a7f9049.png)

can you go to `workspace/models` folder in your inference container and run `ls` and share the print out here? Be sure there are only three models in the `models` folder nothing else than `t4r_pytorch` `t4r_pytorch_nvt` `t4r_pytorch_nvt`.

**Comment by arunslb123** [comment]
![image](https://user-images.githubusercontent.com/3520124/145129012-4ba86983-f54f-42eb-b694-c29097db1b24.png)

@rnyak , I tried updating nvtabular inside the triton container and ended up with this error message. What container are you using in the course? Also I can confirm that I have only 3 folders inside workspace/models.

**Comment by rnyak** [comment]
@arunslb123 sorry for the inconvenience. I am gonna open an issue regarding that at NVTabular GH repo. Hopefully it will be solved shortly.

for the live tutorial we used:
`nvcr.io/nvidia/merlin/merlin-inference:21.09` and `nvcr.io/nvidia/merlin/merlin-pytorch-training:21.09` containers.

with 
`cd /nvtabular && git checkout main`
`pip install pyyaml torchmetrics==0.3.2 tensorflow-metadata ipywidgets transformers==4.9.0`.
`git clone  https://github.com/NVIDIA-Merlin/Transformers4Rec.git && cd Transformers4Rec && pip install -e .`

**Comment by karlhigley** [comment]
A [fix for the NVT issue](https://github.com/NVIDIA-Merlin/NVTabular/pull/1312) was just merged 😅

**Comment by arunslb123** [comment]
@rnyak , I could successfully run end-end notebooks on my A100 40GB GPUs after updating nvtabular to recent versions, and also updating pytorch to pytorch nightly on my triton server containers. 👍 

@karlhigley , thank you very much for fixing the issue. much appreciated :)

**Comment by rnyak** [comment]
@arunslb123 can we close this issue if you are good?

**Comment by arunslb123** [comment]
@rnyak , thank you and happy to close this one.
