### ISSUE TITLE
[QST] How to convert encoded item-ids into original product-ids?

### ISSUE THREAD

**Issue by peterkim95** [NVIDIA-Merlin/Transformers4Rec#352]
# ❓ Questions & Help

## Details

Following along the example notebooks, I am at the stage where I am printing out the top-k predictions:

```
from transformers4rec.torch.utils.examples_utils import visualize_response
visualize_response(filtered_batch, response, top_k=5, session_col='session_id')
'''
- Top-5 predictions for session `11257991`: 2365 || 260 || 196 || 33 || 1169
- Top-5 predictions for session `11270119`: 898 || 2214 || 1169 || 958 || 2814
'''
```

How can I convert these encoded item-ids into the original product-ids? Is there a simple utility function like `idx2word` that can be found with my NVTabular Workflow? It'll also be nice to provide this function for all encoded features like session, category, event_type, etc.

IMO I think the ability to convert indexes into their original words should be added as the final step in these great example notebooks to truly be production-ready.

Thanks!

**Comment by rnyak** [comment]
@peterkim95 we do not currently have a utility function for that mapping. But you can easily use the `unique.item_id.parquet` file in the `categories` folder (if you ran the first NVTabular nb for data processing) for  mapping to the original item ids.

Hopefully we can create such feature or an example with a utility function. You can create a FEA for this feature request. Thanks.

**Comment by rnyak** [comment]
@peterkim95 if my previous answer is fine for you, can we close this issue? you can create a FEA instead.

**Comment by peterkim95** [comment]
Sounds good! I'll create an FEA instead. Thanks for following up

**Comment by SaadAhmed433** [comment]
@rnyak  after reading the `unique.item_id.parquet` file as a cudf dataframe. Does the index of the dataframe refer to the model predicted ids?

**Comment by rnyak** [comment]
You dont get model predicted ids from `unique.item_id.parquet` file. This only gives you your original item_ids in your dataset and their corresponding encoded values. Index column is their encoded values from 1 to N.

your recommended item ids are coming from your  model. You need to convert logit values to meaningful results, i.e., to item_ids
