### ISSUE TITLE
[BUG] importing list_files fails in transformers4rec[pytorch] because of missing TF

### ISSUE THREAD

**Issue by NegatioN** [NVIDIA-Merlin/Transformers4Rec#353]
### Bug description
Installing with `pip install transformers4rec[pytorch]` still makes runs fail with `ModuleNotFoundError: No module named 'tensorflow'` if importing `list_files` from example_utils.

### Steps/Code to reproduce bug
1. `!pip install transformers4rec[pytorch]` 
2. `from transformers4rec.torch.utils.examples_utils import list_files`

Response:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1738/3121253033.py in <module>
----> 1 from transformers4rec.torch.utils.examples_utils import list_files

/opt/conda/envs/test/lib/python3.8/site-packages/transformers4rec/torch/__init__.py in <module>
     19 from ..config.schema import requires_schema
     20 from ..config.trainer import T4RecTrainingArguments
---> 21 from ..config.transformer import (
     22     AlbertConfig,
     23     ElectraConfig,

/opt/conda/envs/test/lib/python3.8/site-packages/transformers4rec/config/transformer.py in <module>
     15 #
     16 
---> 17 import tensorflow as tf
     18 import transformers
     19 

ModuleNotFoundError: No module named 'tensorflow'
```

### Expected behavior
Not failing, because the installation shouldn't require Tensorflow.

### Environment details
- Transformers4Rec version: 0.1.3
- Platform: Linux
- Python version: 3.8
- Huggingface Transformers version: 4.12.5
- PyTorch version (GPU?): 1.10.0+cu113
- Tensorflow version (GPU?): None

**Comment by NegatioN** [comment]
It does seem to be a general thing with v0.1.3.
This fails as well: `from transformers4rec import torch as tr`

**Comment by marcromeyn** [comment]
What version of the code did you use here? From browsing the code in the master-branch, it seems fixed now ([source](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/af63843f83c1e3fef96bce72d4f91711ffa3b489/transformers4rec/config/transformer.py#L21-L24))

**Comment by NegatioN** [comment]
Well, I did use `Transformers4Rec version: 0.1.3` like it says in the post :slightly_smiling_face: But if it's fixed, and will be pushed for the next release, I'm satisfied.

**Comment by rnyak** [comment]
@NegatioN you can simply do

`cd Transformers4Rec
git pull origin main
git checkout main
pip install -e .`

This will pull the latest changes and build the dependencies accordingly.  Please let us know if that works for you.
