### ISSUE TITLE
[BUG] Installing with conda on Windows 10 results in error

### ISSUE THREAD

**Issue by semenoffalex** [NVIDIA-Merlin/Transformers4Rec#365]
### Bug description
After trying `conda install -c nvidia transformers4rec` on Windows 10 I get the following error message:
`UnsatisfiableError: The following specifications were found to be incompatible with each other:`

### Steps/Code to reproduce bug

1. Run Anaconda Prompt
2. Paste & run `conda install -c nvidia transformers4rec`

### Expected behavior
I expect to have transformers4rec to be installed.

### Environment details
- Transformers4Rec version: 
- Platform: Windows 10
- Python version:  3.7.3
- Huggingface Transformers version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

### Additional context
See the screenshot attached.
![2022-02-14_16-57-24](https://user-images.githubusercontent.com/1209785/153878734-e4edbe42-0b99-485f-8b6b-4c2a785e5b34.png)

**Comment by SaadAhmed433** [comment]
Hi, are you able to fix this? I am also running into a similar issue on ubuntu 20

**Comment by gabrielspmoreira** [comment]
@semenoffalex @SaadAhmed433 I also tested the conda install on Ubuntu 20 and got a similar issue (below).
Could you take a look in our Conda package @benfred @albert17 ?

@semenoffalex meanwhile can you try the **pip** install?
I have never tested it on Windows. So you might face many issues on that environment.
Btw, Transformers4Rec uses the GPU-accelerated `nvtabular` data loader, which does not work on Windows. You might want to try and use the "pyarrow" dataloader instead (like [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/1514df4b06523cb7580ef84fcb0c444dce9b1c95/tests/torch/test_trainer.py#L65))

```bash
> conda install -c nvidia transformers4rec

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                           

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

```

**Comment by SaadAhmed433** [comment]
I was able to install the transformers4rec library using pip.

The conda installation wasnt working for me as described here #380 

you can try this: `pip install transformers4rec[pyorch]`

**Comment by viswa-nvidia** [comment]
@semenoffalex , glad you got it working on pip. Please reach out if you need any other help.
