### ISSUE TITLE
Can we modify the algorithm to recommend product on dataset which is single service on single session ?[QST]

### ISSUE THREAD

**Issue by chinmaydas96** [NVIDIA-Merlin/Transformers4Rec#367]
# ❓ Questions & Help

## Details

I want to apply this algorithm in spa service recommendation in which a user books a service in a day.  But in recommendation the sequence of service do matter,  Can it be applied for this scenario ?

**Comment by rnyak** [comment]
@chinmaydas96 can we close this issue?
