### ISSUE TITLE
[DOC] Usage of T5, RoBERTa models as Transformer body in the library

### ISSUE THREAD

**Issue by Ahanmr** [NVIDIA-Merlin/Transformers4Rec#371]
I wished to know, where can I find the documentation for using the other kind of Transformer models such as:
```bash
    BartConfig,
    BertConfig,
    CamembertConfig,
    CTRLConfig,
    DistilBertConfig,
    DPRConfig,
    ElectraConfig,
    FlaubertConfig,
    GPT2Config,
    LayoutLMConfig,
    LxmertConfig,
    OpenAIGPTConfig,
    RobertaConfig,
    T5Config,
```
that are currently not directly available like XLNetConfig, LongformerConfig etc. Is there a tutorial somewhere I can refer? Also is there a way to use a few HuggingFace Transformers that's newly introduced as part of this repo?

**Comment by sararb** [comment]
Thank you for your question, @Ahanmr. Unfortunately, there is not an available tutorial addressing this issue. But you can provide any config of transformer-based language model available in the HuggingFace Transformers library using the [class](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/80596e89977c24736ed5ff22b6fef43fdd6a02f9/transformers4rec/torch/block/transformer.py#L57) ` tr.TransformerBlock(transformer=HF_CONFIG,...)` . 

- Here is an example of how to use `DistilBertConfig`: 
```
from transformers4rec import torch as tr
from transformers import  DistilBertConfig
body = torch4rec.SequentialBlock(
    input_module, tr.TransformerBlock(DistilBertConfig(...), masking=input_module.masking))
model = tr.Head(
            body,
            prediction_task
).to_model()
```

This [table](https://nvidia-merlin.github.io/Transformers4Rec/main/resources.html#supported-huggingface-architectures-and-pre-training-approaches) lists the different configs we tested and their related pre-training tasks. You can also use the newly architectures if they are supporting one of the following pre-training tasks: `mlm`, `clm`, `plm`.
