### ISSUE TITLE
[BUG] UnsatisfiableError:  Unable to install Transformers4Rec

### ISSUE THREAD

**Issue by SaadAhmed433** [NVIDIA-Merlin/Transformers4Rec#380]
### Bug description

Unable to install **Transformers4Rec** using Anaconda on linux based system Ubuntu 20.04.4 LTS

Error msg

```
`Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                   

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
`
```

### Steps/Code to reproduce bug

1. created a new conda environment
2. installed NVTabular and then jupyter notebook via terminal
3. Ran `conda install -c nvidia transformers4rec`

### Environment details
- Transformers4Rec version: N/A
- Platform: Linux Ubuntu 20.04.4 LTS  64bit
- Python version: 3.8.12
- Huggingface Transformers version: N/A
- PyTorch version (GPU?): N/A
- Tensorflow version (GPU?): N/A

**Comment by SaadAhmed433** [comment]
UPDATE: I installed Transformesrs4Rec using `pip install transformers4rec[pyorch]` and then restarted my system. Bot NVtabular and transformers4rec are now working.

**Comment by rnyak** [comment]
@SaadAhmed433 can we close this issue or you still have questions?
