### ISSUE TITLE
[QST] How do I store/save a trained model and then load it later?

### ISSUE THREAD

**Issue by SaadAhmed433** [NVIDIA-Merlin/Transformers4Rec#389]
# ❓ Questions & Help

Probably a very silly a question but I need help in storing a trained model and then loading  it later to make predictions on new unseen data. 

## Details

I trained a model using the `Trainer` class and then I want to save the trained model in my disk and finally  i want to be able to load it in a seperate Jupyter Notebook or code file to actually make predictions on new incoming data. I dont want to use Triton Inference Client, I just want to be able to store the pickle file or whatever and then load it later and use it according to my needs.

Here's the code I am working on

```
train_path = "./data/train_pos/part_0.parquet"
eval_path = "./data/sessions_by_day_mind_1/1/test.parquet"

trainer.train_dataloader = get_dataloader(train_path, train_args.per_device_train_batch_size)
trainer.eval_dataloader = get_dataloader(eval_path, train_args.per_device_eval_batch_size)

trainer.reset_lr_scheduler()

trainer.train()
trainer.state.global_step +=1

# Evaluate
train_metrics = trainer.evaluate(metric_key_prefix='eval')


for key in sorted(train_metrics.keys()):
        print(" %s = %s" % (key, str(train_metrics[key])))
```

So once I have the trainer object trained I now try to save the model using `trainer.save_model(PATH)` but it only stores the dict and not the pickle file. So I am not sure how to go about it. I have looked at the documentation of `hugging face` library as well but I am unable to solve this.

**Comment by rnyak** [comment]
Please try the following:

```
from transformers4rec.torch.trainer import HFWrapper
wrapped_model = HFWrapper(model)
wrapped_model.load_state_dict(torch.load(os.path.join(checkpoint_path, "pytorch_model.bin")))

wrapped_model.eval()

batch=  next(iter(recsys_trainer.get_eval_dataloader()))

with torch.no_grad():
        outputs = model(batch, training=False)
```

**Comment by rnyak** [comment]
@SaadAhmed433  did you see my response above? can we close this issue?
