### ISSUE TITLE
[QST] Embedding as item feature

### ISSUE THREAD

**Issue by kontrabas380** [NVIDIA-Merlin/Transformers4Rec#406]
# ❓ Questions & Help

## Details

Hello,

I'm trying to implement this recommendation system and I have in my dataset item embeddings, which can have useful informations about the item. Is there possibility to use these embeddings as item feature instead of categorical data?

Best regards
K

**Comment by rnyak** [comment]
@kontrabas380 thanks for your question. Currently we do not have an example for adding pre-trained embeddings to the InputBlock, we have an open ticket for that: https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/267

We'll eventually address this FEA request.
