### ISSUE TITLE
Model Eval loss is NaN, if I set input masking method to be casual[BUG]

### ISSUE THREAD

**Issue by john-marinton** [NVIDIA-Merlin/Transformers4Rec#407]
### Bug description
when I set the input masking to casual, it causes eval loss to be NaN, But if I tried with MLM, the pipeline is able compute loss for eval. 

### Steps/Code to reproduce bug

1. Try setting casual or clm in input masking using torch module. 
   inputs= tr.TabularSequenceFeatures.from_schema(
      schema,
      max_sequence_length=sequence_length,
      d_output=d_model,
      aggregation="concat",
      masking="causal",
  )

![image](https://user-images.githubusercontent.com/37063460/163985873-55e08bd5-b5c1-495c-81a2-9c5f2c1555ac.png)

### Environment details
- Transformers4Rec version: 0.1.7
- Platform: Kaggle Jupyter Notebook
- Python version:3.7
- Huggingface Transformers version:4.17.0
- PyTorch version (GPU?):1.9.1

**Comment by rnyak** [comment]
@john-marinton thanks for your interest in the repo. Are you testing any of the examples in the repo? if yes, which notebook? Are you using FP16 optimization? can you share a bit more info?
