### ISSUE TITLE
[QST] Is this the intended behavior of TabularSequenceFeatures.from_schema

### ISSUE THREAD

**Issue by SaadAhmed433** [NVIDIA-Merlin/Transformers4Rec#409]
Hello, I tried to train a model with side features some of the them are continuous and others are categorical features but the continuous features are not becoming a part of the model training because they are not visible in the input block. Here is how I define it

```
sequence_length = 10
inputs = tr.TabularSequenceFeatures.from_schema(
        schema,
        aggregation = "concat",
        max_sequence_length= sequence_length,
        masking = 'clm',
    )
```
**Now when I print the input object I don't see the names of my continuous features**

![image](https://user-images.githubusercontent.com/98022049/167149499-9b6625bd-df23-441c-ae17-a122d6510557.png)

In the `schema` file which was generated when I exported the `workflow` the `annotation` with `continuous` `tags` was missing so I  added it manually but still when I print the input block it does not show me the names of my continuous features. There is just one addition of line which is highlighted in the screenshot.

![image](https://user-images.githubusercontent.com/98022049/167150309-b32df179-0473-4415-b892-22370e3cbf16.png)

Schema file can be reviewed from this [link](https://gist.github.com/SaadAhmed433/aea2d82ec545ef9699c6b370e8e6cd56#file-schema-pbtxt)

Is there a bug or am  I doing something wrong. If I train the model will it use continuous featues?

**Comment by sararb** [comment]
Thank you for your question @SaadAhmed433 !  
Your code is correct.  Unlike the categorical features, the continuous inputs are stacked into one vector and the ContinuousFeatures block outputs one tensor grouping all the raw continuous values. 

To check the name of the continuous features considered in your bock you can print `inputs.to_merge.continuous_module.filter_features.to_include` 

You can also project the raw tensor into a dense vector using the argument `continuous_projection=hidden_dim`  in `TabularSequenceFeatures.from_schema`

**Comment by SaadAhmed433** [comment]
Thanks @sararb
