### ISSUE TITLE
[DOC] Can we use a pre-trained embedding layer in transformers4rec? 

### ISSUE THREAD

**Issue by Jianpeng-Xu** [NVIDIA-Merlin/Transformers4Rec#421]
## Report needed documentation

I was following this example 
https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/03-session-based-XLNet-with-TF.ipynb

One of my use case is to use an NLP pre-trained model (such as USE, BERT, etc.) to generate embedding vectors, and these embedding vectors will serve as one of the input features for transformers4rec. I am not able to find the following:
1. Can we integrate this pre-trained model as one of the bottom layers in transformers4rec? 
2. Can we use NVTabular dataloader to serve inputs containing text strings? 
     - If not, can we present the embedding vector itself in the NVTabular, and NVTabular dataloader, and eventually Transformers4Rec? 

Thanks.

**Comment by Ayush-AgarwalW** [comment]
> NVTabular is designed to handle tabular data, not text. In most cases we've seen where a language model is being used to embed text that's done as a separate process and then the embeddings are fed in. We're working on an example of this for Merlin.

Is there way to use pretrained item embeddings in the architecture though?

**Comment by rnyak** [comment]
@Ayush-AgarwalW yes that's possible with a work around (see [these lines](https://github.com/NVIDIA-Merlin/models/blob/main/tests/unit/tf/inputs/test_embedding.py#L436-L447)). But we did not test this functionality with a high level api. Eventually we are planning to create an example around that task.
