### ISSUE TITLE
[BUG] Cannot install with conda/pip on Ubuntu 20.04 

### ISSUE THREAD

**Issue by future-xy** [NVIDIA-Merlin/Transformers4Rec#424]
### Bug description
Running ```conda install -c nvidia transformers4rec``` gets an error; while running alternative command ```pip install transformers4rec[pytorch,nvtabular]``` gets another error.
### Steps/Code to reproduce bug

1. ```conda create -n trans4rec python=3.8```
2. ```conda activate trans4rec```
3. ```conda install -c nvidia transformers4rec```
4. ```pip install transformers4rec[pytorch,nvtabular]```

### Expected behavior
Transformer4rec should be successfully installed.

### Environment details
- Transformers4Rec version: N/A
- Platform: Ubuntu 20.04
- Python version: Python 3.8.13

### Additional context
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/31511840/170247067-a5a93eac-c342-4473-94c4-5fa116a52c6a.png">

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/31511840/170247094-5b83488b-27a0-46b5-b195-fb64739cbe7f.png">

**Comment by future-xy** [comment]
Running ```pip install transformers4rec[pytorch]``` seems successful. But I got an error when trying to run the PyTorch script in Quick tour.
The python script is
```python
from transformers4rec import torch as tr

schema: tr.Schema = tr.data.tabular_sequence_testing_data.schema
# Or read schema from disk: tr.Schema().from_json(SCHEMA_PATH)
max_sequence_length, d_model = 20, 64

# Define input module to process tabular input-features
input_module = tr.TabularSequenceFeatures.from_schema(
    schema,
    max_sequence_length=max_sequence_length,
    continuous_projection=d_model,
    aggregation="concat",
    masking="causal",
)
# Define one or multiple prediction-tasks
prediction_tasks = tr.NextItemPredictionTask()

# Define a transformer-config, like the XLNet architecture
transformer_config = tr.XLNetConfig.build(
    d_model=d_model, n_head=4, n_layer=2, total_seq_length=max_sequence_length
)
model: tr.Model = transformer_config.to_torch_model(input_module, prediction_tasks)
```

The error shows:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/31511840/170249464-7268c3dd-2bc5-45c2-9c0f-43b007a2ba30.png">

**Comment by EvenOldridge** [comment]
Thanks for taking a look at the library.  We'll look into the install issues, but in the meantime this may help you out with the protobuff issue: https://stackoverflow.com/questions/31308812/no-module-named-google-protobuf

**Comment by rnyak** [comment]
@future-xy can we close this issue if all is good?

**Comment by future-xy** [comment]
> 

To be honest, I still didn't find a way to install all components following the README.md but I tried to use docker, it seems all is fine.

**Comment by viswa-nvidia** [comment]
@bschifferer @rnyak , please review and update the documentation

**Comment by benfred** [comment]
@future-xy We've removed the protoc dependency from nvtabular , you shouldn't see the same build issue in the next release.

What were the other issues that you encountered?

**Comment by future-xy** [comment]
> @future-xy We've removed the protoc dependency from nvtabular in [NVIDIA-Merlin/NVTabular#1566](https://github.com/NVIDIA-Merlin/NVTabular/pull/1566) , you shouldn't see the same build issue in the next release.
> 
> What were the other issues that you encountered?

I just tried and found it seems the first issue I mentioned still exists. That is I can't install with `conda install -c nvidia transformers4rec`, The error is just shown in the figure, <img width="1081" alt="image" src="https://user-images.githubusercontent.com/31511840/170247067-a5a93eac-c342-4473-94c4-5fa116a52c6a.png">

**Comment by oliverholworthy** [comment]
this glibc conflict tripped me up last week. 

One solution I found was to specify `conda-forge` as an additional channel in the install command. This should work:

```sh
conda install -c nvidia -c conda-forge transformers4rec
```

### additional context

I don't fully understand where the source error is coming from (conda install verbose mode doesn't help much). However, I'm pretty sure it's not specific to this project Transformers4Rec. The same glibc error appears to happen for other projects too. 

For example, some [NVIDIA Merlin](http://github.com/NVIDIA-Merlin/) and [RAPIDSAI](https://github.com/rapidsai) libraries ([NVTabular](https://github.com/NVIDIA-Merlin/NVTabular), [merlin-core](https://github.com/NVIDIA-Merlin/core), [cuml](https://github.com/rapidsai/cuml)) report a similar conflict on glibc when installing with the corresponding channel only (`nvidia` and `rapidsai`).

In all these cases, adding `conda-forge` as an additional channel to the install command seems to allow the install to progress.

People have opened issues on various repos with a similar issue (a glibc conflict that doesn't seem to make sense). And so far it doesn't look like anyone has a good explanation for why it's happening.

- cuml:
   https://github.com/rapidsai/cuml/issues/3108
   
- conda:
  https://github.com/conda/conda/issues/11117
  
- pytorch3d:
   https://github.com/facebookresearch/pytorch3d/issues/813

**Comment by viswa-nvidia** [comment]
@mikemckiernan , please add this to the docs

**Comment by mikemckiernan** [comment]
@future-xy , is there any chance that the proposed command with the added `-c conda-forge` argument solves the issue for you?  Thank you.

**Comment by future-xy** [comment]
Yes, I can install transformer4rec by the proposed solution.
