### ISSUE TITLE
Extract similar item from the trained model

### ISSUE THREAD

**Issue by lightsailpro** [NVIDIA-Merlin/Transformers4Rec#425]
Does transformer4rec trained model support  similar item generation based on the item vector like those word2vec model? E.g. for item1, find top k items similar to item1. Thanks

**Comment by lightsailpro** [comment]
Thanks. I will try.

**Comment by dhollier** [comment]
Hi @sararb 

When extracting embeddings this way how can we join in the corresponding item_ids for the embeddings?
