### ISSUE TITLE
[BUG] not able to run basic notebook example for ETL 

### ISSUE THREAD

**Issue by amit-pande-2018** [NVIDIA-Merlin/Transformers4Rec#439]
### Bug description
somehow when i run recency_features = session_ts >> ItemRecency()  in https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb I get the following error:

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [61], in <cell line: 61>()
     57         return np.float64
     59 #session_ts    
     60 #recency_features = ItemRecency(session_ts) 
---> 61 recency_features = session_ts >> ItemRecency()

File /core/merlin/dag/selector.py:128, in ColumnSelector.__rshift__(self, operator)
    124 if isinstance(operator, type) and issubclass(operator, merlin.dag.BaseOperator):
    125     # handle case where an operator class is passed
    126     operator = operator()
--> 128 return operator.create_node(self) >> operator

File /nvtabular/nvtabular/workflow/node.py:29, in WorkflowNode.__rshift__(self, operator)
     23 if callable(operator) and not (
     24     isinstance(operator, type) and issubclass(operator, Operator)
     25 ):
     26     # implicit lambdaop conversion.
     27     operator = LambdaOp(operator)
---> 29 return super().__rshift__(operator)

File /core/merlin/dag/node.py:185, in Node.__rshift__(self, operator)
    182 child.op = operator
    183 child.add_parent(self)
--> 185 dependencies = operator.dependencies()
    187 if dependencies:
    188     if not isinstance(dependencies, collections.abc.Sequence):

TypeError: 'list' object is not callable

### Environment details
- Transformers4Rec version: 
- Platform: 
transformers==4.12.0-e git+https://github.com/NVIDIA-Merlin/Transformers4Rec.git@80596e89977c24736ed5ff22b6fef43fdd6a02f9#egg=transformers4rec

- Python version: Python 3.8.12
- Huggingface Transformers version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

**Comment by gabrielspmoreira** [comment]
This is actually an error with [NVTabular](https://github.com/NVIDIA-Merlin/NVTabular/) and not Transformers4Rec specifically. 
Which version of NVTabular are you using? Have you tried to install its latest version?

**Comment by rnyak** [comment]
@amit-pande-2018 did you solve the issue with the latest NVTabular version?

**Comment by amit-pande-2018** [comment]
The latest docker build works on A100 GPU but not on a MiG stance (Multi-instance GPU). So I have a way to make it work for now!
