### ISSUE TITLE
[QST] Value Counts in Schema File

### ISSUE THREAD

**Issue by jacobdineen** [NVIDIA-Merlin/Transformers4Rec#446]
# ❓ Questions & Help

## Details
```
# packages
transformers4rec[all]==0.1.4
nvtabular==0.9.0
```

Hey team! Thanks again for the great library.
I have been having some issues with automated schema generation via the normal workflow (see below), where a schema.pbtxt file is automatically generated when calling transform on the `workflow` object.

```python
filtered_sessions = self.gen_workflow_graph() # generates end-to-end workflow
dataset = nvt.Dataset(self.df) 
workflow = nvt.Workflow(filtered_sessions)
workflow.fit_transform(dataset).to_parquet(self.output_dir) 
```

With some manual tagging of continuous features, this pretty much outputs what I need it to. The issue arises when trying to construct a model from the same schema file. It seems that features that flow through a `Categorify` workflow node are not automatically computing the `value_count` for that feature and appending it to the schema file. An assertion is thrown when `build` is called (internally) in the final line of the block below. I am thinking that `value_count` plays some role in defining the model architecture, but I was wondering if someone may clarify for me (workaround below shows that valueCounts may be insignificant in model construction, as a null dict also works). 

```python
from transformers4rec import torch as tr

session_max_length=15
d_model:int=64
summary_type:str='first'
transformer_n_head:int=16
transformer_n_layer:int=12
transformer_dropout:float=0.4    

    
input_module = tr.TabularSequenceFeatures.from_schema(
    schema,
    max_sequence_length=session_max_length,
    aggregation=aggregation,
    d_output=d_model,
)

prediction_task = tr.BinaryClassificationTask(target_name='TARGET_max', 
                                              summary_type=summary_type, 
                                              loss=torch.nn.BCELoss())
transformer_config = tr.AlbertConfig.build(
    d_model=d_model, 
    n_head=transformer_n_head, 
    n_layer=transformer_n_layer, 
    dropout = transformer_dropout, 
    total_seq_length=session_max_length
)

model = transformer_config.to_torch_model(input_module, prediction_task)
```

For instance, if a schema file contains the following it will not compile:

```
feature {
  name: "variant-list"
  type: INT
  int_domain {
    name: "variant-list"
    min: 0
    max: 14
    is_categorical: true
  }
  annotation {
    tag: "list"
    tag: "categorical"
  }
}
```

But a feature specified like this will:
```
feature {
  name: "variant-list"
  value_count {
    min: 1
    max: 100
  }
  type: INT
  int_domain {
    name: "variant-list"
    min: 0
    max: 14
    is_categorical: true
  }
  annotation {
    tag: "list"
    tag: "categorical"
  }
}
```

Temporary workaround is to manipulate the schema file to contain an empty dict rewrapped in `Schema`, and which point the issue above goes away:
```python
from merlin_standard_lib import Schema, Tag

    def get_schema(self, df: cudf.DataFrame, features_to_drop: list) -> Schema:
        cols = [i for i in df.columns if i not in features_to_drop]
        schema = Schema().from_proto_text(f"{self.output_dir}/{self.schema_path}")

        # bug where 'value_count is not added as a tag for categorical features?'
        schema_dict = schema.to_dict()
        for i in schema_dict["feature"]:
            try:
                if "categorical" in i["annotation"]["tag"]:
                    i["valueCount"] = {}
            except:
                continue

        return Schema().from_dict(schema_dict).select_by_name(cols)
```

**Comment by sararb** [comment]
Thank you @jacobdineen for your questions! 

1. Regarding your point `It seems that features that flow through a Categorify workflow node are not automatically computing the value_count for that feature and appending it to the schema file.` : 

     --> Indeed, the Categorify op does not automatically detect the list features and consequently won't compute the min/max lengths of the ValueCount field. For that you will need to add a `ValueCount` operation to your workflow, as follows: 
```val_count_feats = features['list_feat1', 'list_feat2', ...] >> nvt.ops.ValueCount()```


2. Regarding your point `I am thinking that value_count plays some role in defining the model architecture, but I was wondering if someone may clarify for me `:

     --> The value_count is needed to infer the list features and their shapes (when max_sequence_length is not specified). You can check [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/1514df4b06523cb7580ef84fcb0c444dce9b1c95/transformers4rec/torch/utils/torch_utils.py#L143) the method that uses the `value_count` field.  In other terms,  we need the field `value_count` to indicate that the feature is a list column. But we need the max field value only when `max_sequence_length` is not specified.
