### ISSUE TITLE
[BUG] Error running ETL with NVTabular tutorial notebook -- version compatibility issue?

### ISSUE THREAD

**Issue by hui-wan** [NVIDIA-Merlin/Transformers4Rec#480]
### Bug description

When running `02-ETL-with-NVTabular.ipynb` on REES46 data, the following error was reported:
```
Failed to transform operator <nvtabular.ops.groupby.Groupby object at 0x7f62fed519a0>
Traceback (most recent call last):
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/workflow/workflow.py", line 519, in _transform_partition
    output_df = node.op.transform(selection, input_df)
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/ops/groupby.py", line 132, in transform
    new_df = _apply_aggs(
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/ops/groupby.py", line 244, in _apply_aggs
    df[f"{col}{name_sep}{_agg}"] = _first_or_last(
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/ops/groupby.py", line 288, in _first_or_last
    return _first(x)
  File "/home/hwan/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/ops/groupby.py", line 302, in _first
    return elements[offsets[:-1]]
TypeError: 'NumericalColumn' object is not subscriptable
....
File ~/miniconda3/envs/trans4rec/lib/python3.9/site-packages/nvtabular/ops/groupby.py:302, in _first(x)
    300     offsets = x.list._column.offsets
    301     elements = x.list._column.elements
--> 302     return elements[offsets[:-1]]
    303 else:
    304     # cpu/pandas
    305     return x.apply(lambda y: y[0])

TypeError: 'NumericalColumn' object is not subscriptable
```

### Steps/Code to reproduce bug

1. Loading REES `Oct-2019.parquet` into `examples/tutorial/02-ETL-with-NVTabular.ipynb`
2. Run the cells until hitting the cell right beneath `Initialize the NVTabular dataset object and workflow graph.`

### Expected behavior

The workflow is expected to fit and transform the data  without error.

### Environment details
- Transformers4Rec version: The current codebase from Github (commit 0fd858dcee5ce5b2508f7e91733ae68710affd76)
- Platform: Ubuntu 18.04
- Python version: 3.9
- Huggingface Transformers version: 4.18
- PyTorch version (GPU?): 1.12 (GPU)
- Tensorflow version (GPU?): 
- NVTabular version: 1.3.3
- CUDF version: 22.08 (cuda version, from rapidsai)

### Additional context

I am suspecting it might be compatibility issues related to NVTabular and CUDF versions. Much appreciate your help! Thanks!

**Comment by rnyak** [comment]
@hui-wan thanks for reporting that. Can you please rerun the [01-preprocess.ipynb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/01-preprocess.ipynb) notebook and generate the `Oct-2019.parquet` parquet file at your end before you execute `02-ETL-with-NVTabular.ipynb` notebook.  Let us know if you still hit any issues after following these steps.

**Comment by hui-wan** [comment]
@rnyak Thank you for your timely response. I reran [01-preprocess.ipynb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/01-preprocess.ipynb) notebook and generated the Oct-2019.parquet. However, executing `02-ETL-with-NVTabular.ipynb` still triggers the same error. -- I added the summary trace-back in the first post above, in case that would be helpful. -- Could it be the NVTabular/CUDF version issue? Thanks!

**Comment by rnyak** [comment]
@hui-wan which env are you using? Are you using docker image? if yes please use `merlin-pytorch:22.07` image. If not docker, how did you install NVTabular and Transformers4Rec? Are you running ETL notebook on GPU or CPU? thanks.

**Comment by hui-wan** [comment]
@rnyak I am using a virtual environment. 

- NVTabular was installed when creating the environment 
```
conda create -n trans4rec  -c rapidsai -c numba -c nvidia -c pytorch -c conda-forge  nvtabular    cudf=22.08 python=3.9 pytorch cudatoolkit=11.3
```

- Transformers4Rec was installed from source code by `pip install -e Transformers4Rec`.

- I am running ETL notebook on GPU. 

Thanks!

**Comment by rnyak** [comment]
@hui-wan  can you install `cudf=22.04` in your conda install command instead of  ` cudf=22.08` ? Besides is there a possibility you can work on a docker container? you can simply do that  to pull the docker image.

`docker pull nvcr.io/nvidia/merlin/merlin-pytorch:22.07`

**Comment by benfred** [comment]
I believe this issue is fixed with https://github.com/NVIDIA-Merlin/NVTabular/pull/1654 - this will be in the next release of nvtabular

**Comment by hui-wan** [comment]
Thank you very much for your help @benfred and @rnyak. (Been out for a few days so did not reply earlier.) Looking forward to the fix roll-out of NVTabular!

**Comment by hui-wan** [comment]
Update: The issue went away with the installation of the latest NVTabular version 1.4.0 released on 09/06/2022.

Thank you for your help @benfred @rnyak!
