### ISSUE TITLE
[Task] Import Dataset class from merlin.io instead of nvtabular.io

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#484]
### Description
Currently `Dataset` class is imported from `nvtabular.io` as in here https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/merlin_standard_lib/utils/misc_utils.py#L199, but we should change this to  `from merlin.io import Dataset`.

**Comment by TassaraR** [comment]
+1 
Just had an ImportError while trying to run https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb and this seems to be the issue.

**Comment by rnyak** [comment]
@TassaraR  I think, you would not get an import issue regarding the ticket I mention above. Because, nvtabular.io.Dataset is just an alias for merlin.io.Dataset. 

Can you please share what error issue you got? give more details regarding your env? do you use docker image? if yes which one? if not, how did you install TF4Rec and NVT? and do you run things on GPU? Thanks.

**Comment by TassaraR** [comment]
@rnyak 

I installed everything using conda (on a new conda environment) as recommended in the rapidsai website, nvtabular github and t4rec github. I'm currently running the code on a Google's Vertex AI Workbench notebook with a Nvidia Tesla T4 GPU on ubuntu 20.04.

I'm not currently using the docker image but I used it successfully a couple of weeks ago on my own machine (But I shouldn't use it for my current use case)

I'm using nvtabular 1.4.0 and t4rec 0.1.4 which should be the latest versions available from conda.

When trying to run this chunk of code from https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb I get the following error:

```python3
%%time
start_time_window_index = 1
final_time_window_index = 7
#Iterating over days of one week
for time_index in range(start_time_window_index, final_time_window_index):
    # Set data 
    time_index_train = time_index
    time_index_eval = time_index + 1
    train_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_train}/train.parquet"))
    eval_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_eval}/valid.parquet"))
    print(train_paths)
    
    # Train on day related to time_index 
    print('*'*20)
    print("Launch training for day %s are:" %time_index)
    print('*'*20 + '\n')
    trainer.train_dataset_or_path = train_paths
    trainer.reset_lr_scheduler()
    trainer.train()
    trainer.state.global_step +=1
    print('finished')
    
    # Evaluate on the following day
    trainer.eval_dataset_or_path = eval_paths
    train_metrics = trainer.evaluate(metric_key_prefix='eval')
    print('*'*20)
    print("Eval results for day %s are:\t" %time_index_eval)
    print('\n' + '*'*20 + '\n')
    for key in sorted(train_metrics.keys()):
        print(" %s = %s" % (key, str(train_metrics[key]))) 
    wipe_memory()
```

```
ValueError: NVTabular is necessary for this function, please install: nvtabular.
```

When reading the traceback it can be infered that this is an issue with the io.py file inside the nvtabular package.

```
ModuleNotFoundError                       Traceback (most recent call last)
File /opt/conda/envs/rapids-22.08/lib/python3.9/site-packages/merlin_standard_lib/utils/misc_utils.py:199, in validate_dataset(paths_or_dataset, batch_size, buffer_size, engine, reader_kwargs)
    198 try:
--> 199     from nvtabular.io.dataset import Dataset
    200 except ImportError:

ModuleNotFoundError: No module named 'nvtabular.io.dataset'; 'nvtabular.io' is not a package
```

I can import from io by doing
```python3
from nvtabular.io import dataset
```

But I get the same error if I try the import described in the traceback
```
ModuleNotFoundError: No module named 'nvtabular.io.dataset'; 'nvtabular.io' is not a package
```

**Comment by rnyak** [comment]
@TassaraR  What happens when you run `import nvtabular as nvt`?  does that work for you? if not, that means NVTabular was not installed properly.

**Comment by samhedin** [comment]
Here's some info that I wrote down in a different place:
### Bug description

This does not work: https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
This crashes
``` python
T4RecTrainingArguments(data_loader_engine='nvtabular',
                                    dataloader_drop_last = True,
                                    gradient_accumulation_steps = 1,
                                    per_device_train_batch_size = 128,
                                    per_device_eval_batch_size = 32,
                                    output_dir = "./tmp",
                                    learning_rate=0.0005,
                                    lr_scheduler_type='cosine',
                                    learning_rate_num_cosine_cycles_by_epoch=1.5,
                                    num_train_epochs=5,
                                    max_sequence_length=20,
                                    report_to = [],
                                    logging_steps=50,
                                    no_cuda=False)
```
with error message `ValueError: NVTabular is necessary for this function, please install: nvtabular.`
The error originates from `~/.conda/envs/<env>/lib/python3.9/site-packages/merlin_standard_lib/utils/misc_utils.py`:
``` python
    try:
        from nvtabular.io.dataset import Dataset
    except ImportError:
        raise ValueError("NVTabular is necessary for this function, please install: " "nvtabular.")
```
Therefore, you can trigger the same error by running `from nvtabular.io.dataset import Dataset` 
which leads to `ModuleNotFoundError: No module named 'nvtabular.io.dataset'; 'nvtabular.io' is not a package`

`nvtabular.io.dataset` does not exist.  `nvtabular.io` exists but is deprecated:
``` python
# nvtabular.io
# Re-export classes/modules from the core library for backwards compatibility
from merlin.io import *  # noqa

warnings.warn(
    "The `nvtabular.io` module has moved to `merlin.io`. "
    "Support for importing from `nvtabular.io` is deprecated, "
    "and will be removed in a future version. Please update "
    "your imports to refer to `merlin.io`.",
    DeprecationWarning,
)
```

The error can be solved by changing the import inside `~/.conda/envs/<env>/lib/python3.9/site-packages/merlin_standard_lib/utils/misc_utils.py`:
``` python
    try:
        from merlin.io.dataset import Dataset
    except ImportError:
        raise ValueError("NVTabular is necessary for this function, please install: " "nvtabular.")
```

### Environment details
``` python
  name: merlin-core
  optional: false
  platform: linux-64
  url: https://conda.anaconda.org/nvidia/noarch/merlin-core-0.7.0-py_0.tar.bz2
  version: 0.7.0
- category: main
  dependencies:
    cudf: '>=21.10.*'
    cupy: '>=7.2.0,<10.0.0a'
    dask-cudf: '>=21.10.*'
    merlin-core: '>=0.2.0'
    nvtx: '>=0.2.1'
    pynvml: ''
    python: '>=3.9,<3.10.0a0'
    scipy: ''
  hash:
    md5: e550b104fb3a49dda53dca78099fdeaf
    sha256: ea269c8f002d8a5805080e7eb9e5e457ce1caaeb79bb3a9b2009816e2d65da20
  name: nvtabular
  optional: false
  platform: linux-64
  url: https://conda.anaconda.org/nvidia/linux-64/nvtabular-1.5.0-py39_0.tar.bz2
  version: 1.5.0

```

**Comment by samhedin** [comment]
> @TassaraR I think, you would not get an import issue regarding the ticket I mention above. Because, nvtabular.io.Dataset is just an alias for merlin.io.Dataset.

`merlin.io.Dataset` does not exist, it's `merlin.io.dataset.Dataset` that should be imported.

**Comment by rnyak** [comment]
@samhedin we do use `merlin.io.Dataset`, so it does exist. check this [example](https://github.com/NVIDIA-Merlin/models/blob/main/examples/02-Merlin-Models-and-NVTabular-integration.ipynb)

we can import Dataset as `from merlin.io.dataset import Dataset`.

**Comment by samhedin** [comment]
> @samhedin we do use `merlin.io.Dataset`, so it does exist. check this [example](https://github.com/NVIDIA-Merlin/models/blob/main/examples/02-Merlin-Models-and-NVTabular-integration.ipynb)
> 
> we can import Dataset as `from merlin.io.dataset import Dataset`.

That's interesting! Doing said modification solves my issue, maybe a question of version(s)?
