### ISSUE TITLE
[Task] Compare models trained with single GPU, DataParallel and DistributedDataParallel with Trainer (NextItemPredictionTask)

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Transformers4Rec#488]
### Description
This task is to benchmark the runtime and average examples per second of the following configurations for REES46 for the `NexItemPredictionTask` using the `Trainer`:
- Single GPU
- Multi-GPU with `DataParallel` (2 and 4 GPUs)
- Multi-GPU with `DistributedDataParallel`  (2 and 4 GPUs)

**Comment by rnyak** [comment]
@nzarif and @gabrielspmoreira  We also need clear definitions and steps for users how to train a TF4Rec PyT model with DP and DDP after the PRs are merged. an example script with explanations in the README would be useful, once we have all the functionalities.
