### ISSUE TITLE
[Task] Add Example for Transformer4Rec Serving Example

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Transformers4Rec#491]
### Description
Providing a Serving Example Transformer4Rec

Dependent on :  https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/507

**Comment by rnyak** [comment]
@bschifferer  is that with Merlin Systems and Torch backend?

**Comment by rnyak** [comment]
related to that https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/499

**Comment by viswa-nvidia** [comment]
We ahve an example with python backend. This example with torch script.

**Comment by viswa-nvidia** [comment]
@bschifferer , please tag the PR to this ticket

**Comment by viswa-nvidia** [comment]
Example is done for serving the model

**Comment by rnyak** [comment]
The model serving example was merged via this PR https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/552.
