### ISSUE TITLE
[Task] Transformers4Rec Serving using Merlin Schema

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA-Merlin/Transformers4Rec#499]
- [x] Saving Merlin input and output schema when saving the model

**Comment by viswa-nvidia** [comment]
Moving this to T4R repo.

**Comment by sararb** [comment]
I updated the task description, as what is needed for T4Rec serving is saving input and output merlin-core schemas. This fix #507 implements input/output_schema methods in T4Rec that build the schemas using the merlin-core Schema class.  

Removing the merlin-standard dependency is a breaking change that will require a larger refectory of multiple T4Rec blocks.  and is outside of the scope of this ticket.
