### ISSUE TITLE
Example of dataloading pretrained embeddings in Transformers4Rec

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Transformers4Rec#501]
- [ ] Add an example to use pre-trained embeddings as an embedding table
- [ ] Extend the example: Add an example for usage of pre-trained embeddings with session-based recommendation (e.g. SIGIR Challenge dataset). We will add serving with for this example, as well.

**Comment by karunaahuja** [comment]
do we have such an example yet?
