### ISSUE TITLE
[Task] Add multi-GPU example for Transformer4Rec PyTorch

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Transformers4Rec#508]
### Description

- [ ] Add NVTabular issue here

https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/508#tasklist-block-cf68cea9-27c1-495c-bf46-08e59b64142b

**Comment by rnyak** [comment]
when pulling the latest nvtabular main branch, we get error in the transformers4rec training loop.

**Comment by rnyak** [comment]
The example was created via this PR https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/521 and it was working fine, however recent changes in data loader break the example. So we created this bug ticket https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/526.
