### ISSUE TITLE
[QST] Example tutorial: inference for sessions with 1 interaction

### ISSUE THREAD

**Issue by denisov-vlad** [NVIDIA-Merlin/Transformers4Rec#512]
# ❓ Questions & Help

## Details

Tutorial folder: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/tutorial

Step 2: drop sessions with less than 2 interactions:
```
filtered_sessions = selected_features >> nvt.ops.Filter(f=lambda df: df["product_id-count"] >= MINIMUM_SESSION_LENGTH)
```

The workflow is designed to be the same at the inference level. So, if we have session with 1 interaction, the output for this session will be empty.

Is it possible to use different workflow for training and inference?

I've set `MINIMUM_SESSION_LENGTH=1`. Is it ok?

**Comment by rnyak** [comment]
it should be fine. you dont even have to set `MINIMUM_SESSION_LENGTH` and you can skip `iltered_sessions = selected_features >> nvt.ops.Filter(f=lambda df: df["product_id-count"] >= MINIMUM_SESSION_LENGTH)` step in NVT workflow at your end.
