### ISSUE TITLE
[BUG] Key Error while running Triton Inference on Tutorial Notebooks

### ISSUE THREAD

**Issue by vatsalmpatel** [NVIDIA-Merlin/Transformers4Rec#534]
### Bug description
Getting key error when trying to get inferences following the tutorial on the trans4rec GitHub page.

### Steps/Code to reproduce bug

1. using merlin-tensorflow:22.09 container and then pip installing PyTorch inside the container
2. Following this tutorial: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/tutorial. When running the inference with triton notebook (4th notebook) I am getting this error shown in the screenshot below.
<img width="1682" alt="Screen Shot 2022-11-14 at 1 51 34 PM" src="https://user-images.githubusercontent.com/59699558/202001496-0acc8676-b142-469e-ac64-4a99412fa3c7.png">
3. Followed previous 3 notebooks and getting error in the 4th notebook

### Expected behavior

Should give inferences like the ones showed in the notebook.

### Environment details
- using the merlin-tensorflow:22.09 container with nvtabular, transformers4rec and all the other libraries that come with the container
- training on 4x Nvidia V100 GPU's and using the same compute for inferences as well.
- using container from here: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-tensorflow

**Comment by rnyak** [comment]
@vatsalmpatel I responded you in another thread. Can you please use `merlin-pytorch:22.11` container and please do not install torch since it has torch, transformers etc already installed. Let us know if `22.11` container works for you. thanks.

**Comment by rnyak** [comment]
@vatsalmpatel I ran the tutorial notebooks as well, in `merlin-pytorch:22.11` container and all worked fine. I only did a dtype change in the `02-ETL` notebook like below: 

```
# Relative price to the average price for the category_id
def relative_price_to_avg_categ(col, gdf):
    epsilon = 1e-5
    col = ((gdf['price'] - col) / (col + epsilon)) * (col > 0).astype(int)
    return col.astype(np.float32)
```

Please try that and let us know if that solves your issue. Please use latest stable merlin pytorch container. thanks!

**Comment by vatsalmpatel** [comment]
I will try this and let you know by tomorrow day end.

**Comment by vatsalmpatel** [comment]
@rnyak I am still getting the same error. I am going to share my notebooks with you that I use. There is one change that I make in the 02 ETL notebook, because the notebook do not generate schema file on its own, I use this piece of code to generate the schema file. 

```
# Schema Generating code

dataset = nvt.Dataset(df)

workflow = nvt.Workflow(filtered_sessions)
workflow.fit(dataset)
sessions_gdf = workflow.transform(dataset).to_parquet(
    output_path=os.path.join('./', "train"),
    out_files_per_proc=1,
    shuffle=False
)
sessions_gdf = workflow.transform(dataset).to_ddf()
```

But, when I go to run the training notebook `03 Session Based Notebook`, and run the cell with this code

```
# Reading in the schema file
sequence_length = 20
inputs = tr.TabularSequenceFeatures.from_schema(
        schema,
        max_sequence_length= sequence_length,
        masking = 'causal',
    )
```

I get this error, 
```
ValueError: For masking a categorical_module is required including an item_id.
```
Here is the snippet where I make the change in the schema file, the tag "item_id" in annotation did not get generated automatically, I had to manually put it in there.

```
feature {
  name: "product_id-list_seq"
  value_count {
  }
  type: INT
  int_domain {
    name: "product_id"
    max: 118334
    is_categorical: true
  }
  annotation {
    tag: "categorical"
    tag: "list"
    tag: "item_id"
    extra_metadata {
      type_url: "type.googleapis.com/google.protobuf.Struct"
      value: "\nG\n\017embedding_sizes\0224*2\n\026\n\tdimension\022\t\021\000\000\000\000\000\000\200@\n\030\n\013cardinality\022\t\021\000\000\000\000\360\343\374@\n\r\n\007is_list\022\002 \001\n\025\n\010max_size\022\t\021\000\000\000\000\000\000\000\000\n\034\n\017dtype_item_size\022\t\021\000\000\000\000\000\000P@\n\021\n\013num_buckets\022\002\010\000\n\033\n\016freq_threshold\022\t\021\000\000\000\000\000\000\000\000\n\017\n\tis_ragged\022\002 \000\n\030\n\013start_index\022\t\021\000\000\000\000\000\000\360?\n5\n\010cat_path\022)\032\'.//categories/unique.product_id.parquet"
    }
  }
}
```

So, then I go and manually add this tag in the schema file. So, everything trains fine, but I get the same `GELU Activation error` during inferencing. Just to make it more clear, I am not using the schema file that you guys provide in the repo, I am using code to generate the schema file automatically.

I am attaching a bunch of things here, the notebooks that I use and the schema file that is generated when I run the code above. I think you would be able to replicate the same error I am getting with this. If not, we can hop on a call and explain it to you more clearly. Let me know what you think.

I am attaching a zip file, so you can use all the scripts and hopefully generate the same error that I am getting.
[scripts.zip](https://github.com/NVIDIA-Merlin/Transformers4Rec/files/10125474/scripts.zip)

**Comment by rnyak** [comment]
@vatsalmpatel  you need to tag features properly in the ETL notebook if you want to generate the schema from NVTabular. Please follow this [example](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb) to see how to do so.

**Comment by vatsalmpatel** [comment]
@rnyak I used the schema file that is there in the repo, literally copy and pasted it, still it dosen't work. On thing to note is that I am not running this locally, I am running it on Azure Machine Learning studio.

**Comment by rnyak** [comment]
@vatsalmpatel sorry, I am confused. why did you say `because the notebook do not generate schema file on its own, I use this piece of code to generate the schema file.`?  there is a schema file alreadyL https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/schema_tutorial.pb
and the schema file here is correct.

why dont you use it as it is?

**Comment by rnyak** [comment]
Please do not share your code as zip file. share in a github gist so we can take a look, thanks.

**Comment by rnyak** [comment]
@vatsalmpatel hello. did you solve your issue? are you still getting an error?

**Comment by rnyak** [comment]
@vatsalmpatel I am closing this issue since we did not hear from you. please reopen if you need to.
