### ISSUE TITLE
[BUG] Transformer4Rec training examples are broken

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Transformers4Rec#565]
### Bug description
If I pull the latest version of all Merlin libraries in the pytorch:22.11 container and try to run https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based - the example is broken.

The reason is that dataloader returns a tuple instead of a dense tensor. Latest commit updated the Transformer4Rec (and NVTabular) to use the new dataloader package.

Another bug is, that `from merlin.dataloader.torch import Loader` cannot be found
https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/transformers4rec/torch/utils/data_utils.py#L175

**Comment by sararb** [comment]
Thank you for reporting this bug! can you share the error stack you are getting? 
Regarding the import error: `from merlin.dataloader.torch import Loader`, can you check if the data loader is installed in your environment?
