### ISSUE TITLE
[FEA] Update Transformers4Rec to use merlin core schema 

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/Transformers4Rec#566]
# 🚀 Feature request
Remove merlin-standardlib dependency and use the merlin-core schema instead.  

## Motivation
The merlin-standard lib has an old schema, that is not maintained. As the Merlin framework has now a `merlin-core` library that provides a Schema class and the related Tags. The latter schema is the one produced by Merlin NVTabular and also used by Merlin Systems for serving. So to maintain a seamless integration between T4Rec, NVTabular, and Systems, we should update T4Rec to use the same schema class used by NVTabular and Systems. 

## Scope
- [ ] Change notebooks to use merlin core schema
- [ ] Deprecation warnings

**Comment by nv-alaiacano** [comment]
I see these 3 PRs related to this. Can we close this ticket?

* https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/642
* https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/634
* https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/632
