### ISSUE TITLE
[BUG] When running the example with the synthetic dataset in Session-based Rec with XLNET, I get an error with trainer.evaluate(). I get the expected output in the other cells. The error is  "IndexError: too many indices for tensor of dimension 2"

### ISSUE THREAD

**Issue by enislalmi** [NVIDIA-Merlin/Transformers4Rec#575]
### Steps/Code to reproduce bug

1. An error becomes present when running trainer.evaluate(metric_key_prefix=eval). Everything else is the same as in notebook https://nvidia-merlin.github.io/Transformers4Rec/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.html. Everything else has the expected output.

### Expected behavior

Normally, after training (which works fine) I should get the eval results.

### Environment details
- Transformers4Rec version: 0.1.15
- Platform: Windows
- Python version: 3.7.12
- Huggingface Transformers version: 1.0
- PyTorch version (GPU?): GPU T4
- Tensorflow version (GPU?):

**Comment by enislalmi** [comment]
dependecies issues. Torchmetrics werent up to date.

**Comment by ravikant15796** [comment]
@enislalmi I have upgraded Torchmetrics to 0.11.0 but still getting same issue

**Comment by rnyak** [comment]
@ravikant15796 what's your error? what env you are running the examples in? are you using docker image? or?
