### ISSUE TITLE
ImportError: cannot import name '_LazyModule' from 'transformers.file_utils' (/opt/conda/lib/python3.7/site-packages/transformers/file_utils.py)

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/Transformers4Rec#578]
### Bug description
Import error while importing transformer4rec library

Updated the dependent libraries like torch, torchmetrics to latest version still facing while running below code
**import transformers4rec.torch as tr**
error
![image](https://user-images.githubusercontent.com/48671630/207628118-646d028b-6996-4a7f-906d-ed328c8e939a.png)

### Environment details
- Transformers4Rec version: 0.15.0
- Platform: Kaggle Notebook
- Python version: 3.7.12

**Comment by rnyak** [comment]
@DilipKumar3 hello. are you still getting import error? if not can we close this ticket?

**Comment by DilipKumar3** [comment]
You can close this ticket. I installed by specifying the version  and it worked
