### ISSUE TITLE
what does Schema().from_proto_text(SCHEMAPATH) does ?

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/Transformers4Rec#579]
# ❓ Questions & Help
What does the below line of code does ?
![image](https://user-images.githubusercontent.com/48671630/207633092-52652cf5-93a8-4a86-8bba-fe447e30c02a.png)
do the code expect file in the specified path or it will write a schema in the path  ?

## Details
im facing issue while running the above code
![image](https://user-images.githubusercontent.com/48671630/207633948-6c1a831e-7563-4ba1-9e39-857d1aaff62f.png)
![image](https://user-images.githubusercontent.com/48671630/207634022-93e011b9-e140-4e4c-b445-5f5e8c0fbc1f.png)

**Comment by rnyak** [comment]
@DilipKumar3  hello.  `do the code expect file in the specified path` 
Yes. it does expect you have a schema file in the given path. You either generate a schema file manually as in the example folder, or you generate it via NVTabular (check this [getting-started ETL notebook](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb) how).

the error you get should be related to setting the path of the schema properly.
