### ISSUE TITLE
[QST]ValueError: For masking a categorical_module is required including an item_id.

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/Transformers4Rec#581]
# ❓ Questions & Help
Im trying to understand Transform4Rec model. so im running the model building Script based on e-commerce data https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/01-preprocess.ipynb 
while running im stuck with below exception 
## Details
![image](https://user-images.githubusercontent.com/48671630/208090054-8f1f3373-f3e7-4b87-9c6d-25421f24754e.png)

Trying to understand what does this set of code does here. and what was the issue here ?

**Comment by rnyak** [comment]
>Trying to understand what does this set of code does here. and what was the issue here ?
One issue might be your schema file does not have `item_id` tag for your item_id column. do you have the tag there? if yes, can you please print your schema and paste it here? 

How do you generate schema file? do you use the existing schema file in the folder?  did you run the ETL notebook first? did you change anything in the notebooks? Thanks.

**Comment by DilipKumar3** [comment]
i ran the code sequentially only. how do we tag a feature is item_id ? 

let's take my item_id feature is **merchant_id**. how can i specify this feature tag ?

**Comment by DilipKumar3** [comment]
Thank you for the info .
