### ISSUE TITLE
[BUG] RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by bishnarender** [NVIDIA-Merlin/Transformers4Rec#583]
# code
    %%time
    start_time_window_index = 1
    final_time_window_index = 37
    #Iterating over days 
    for time_index in range(start_time_window_index, final_time_window_index):
        # Set data 
        time_index_train = time_index
        time_index_eval = time_index + 1
        train_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_train}/train.parquet"))
        eval_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_eval}/valid.parquet"))
        print(train_paths)
        
        # Train on day related to time_index 
        print('*'*20)
        print("Launch training for day %s are:" %time_index)
        print('*'*20 + '\n')
        trainer.train_dataset_or_path = train_paths
        trainer.reset_lr_scheduler()
        trainer.train()
        trainer.state.global_step +=1
        print('finished')
        
        # Evaluate on the following day
        trainer.eval_dataset_or_path = eval_paths
        train_metrics = trainer.evaluate(metric_key_prefix='eval')
        print('*'*20)
        print("Eval results for day %s are:\t" %time_index_eval)
        print('\n' + '*'*20 + '\n')
        for key in sorted(train_metrics.keys()):
            print(" %s = %s" % (key, str(train_metrics[key]))) 
        wipe_memory()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <timed exec>:18

File ~/miniconda3/lib/python3.9/site-packages/transformers/trainer.py:1422, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1420         tr_loss_step = self.training_step(model, inputs)
   1421 else:
-> 1422     tr_loss_step = self.training_step(model, inputs)
   1424 if (
   1425     args.logging_nan_inf_filter
   1426     and not is_torch_tpu_available()
   1427     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1428 ):
   1429     # if loss is nan or inf simply add the average of previous logged losses
   1430     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File ~/miniconda3/lib/python3.9/site-packages/transformers/trainer.py:2031, in Trainer.training_step(self, model, inputs)
   2027             loss = self.deepspeed.backward(loss)
   2028         else:
   2029 # edited by narender bishnoi                
   2030 #1            loss.backward()
-> 2031             loss.backward()
   2033         return loss.detach()

File ~/miniconda3/lib/python3.9/site-packages/torch/_tensor.py:396, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    387 if has_torch_function_unary(self):
    388     return handle_torch_function(
    389         Tensor.backward,
    390         (self,),
   (...)
    394         create_graph=create_graph,
    395         inputs=inputs)
--> 396 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

File ~/miniconda3/lib/python3.9/site-packages/torch/autograd/__init__.py:166, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    162 inputs = (inputs,) if isinstance(inputs, torch.Tensor) else \
    163     tuple(inputs) if inputs is not None else tuple()
    165 grad_tensors_ = _tensor_or_tensors_to_tuple(grad_tensors, len(tensors))
--> 166 grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
    167 if retain_graph is None:
    168     retain_graph = create_graph

File ~/miniconda3/lib/python3.9/site-packages/torch/autograd/__init__.py:67, in _make_grads(outputs, grads, is_grads_batched)
     65 if out.requires_grad:
     66     if out.numel() != 1:
---> 67         raise RuntimeError("grad can be implicitly created only for scalar outputs")
     68     new_grads.append(torch.ones_like(out, memory_format=torch.preserve_format))
     69 else:

RuntimeError: grad can be implicitly created only for scalar outputs

**Comment by rnyak** [comment]
@bishnarender hello. we need more info to be able to address your issue. what's your env? how did you install Transformers4rec, NVtabular, core and dataloader libraries? you need all of them. I think you are not using docker image, do you? so please install the latest versions of these libraries.

Are you using your custom dataset? if yes, how did you generate your schema file? and what's your schema file look like?

can you please first run the notebook `01` and `02` in this [folder](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based) in your env without changing anything (except the data path) and see if you are getting any errors? if yes, that means you need to reinstall the libraries in a clean env.  If no, that means something in your custom code (may be in your ETL or your schema file is not accurate).

**Comment by bishnarender** [comment]
Problem solved with python 3.7.12. Thanks !!
