### ISSUE TITLE
[QST] what is output predictions meaning?

### ISSUE THREAD

**Issue by DH-HAN** [NVIDIA-Merlin/Transformers4Rec#594]
# ❓ Questions & Help
When i  Put just one data to my trained Model,l

{'Click_Rank-list_seq': tensor([[15, 15, 15, 14, 15, 15, 15, 13, 15, 13, 15, 15, 14, 14, 15, 13, 14, 14,
          14, 14]], device='cuda:0'),
 'Carts_Rank-list_seq': tensor([[ 9, 10, 10,  9,  9,  9, 10,  5,  9,  5,  3,  8,  7,  8, 10,  9,  9,  9,
           9,  9]], device='cuda:0'),
 'Orders_Rank-list_seq': tensor([[3, 9, 0, 4, 2, 2, 5, 0, 8, 0, 0, 1, 1, 1, 9, 1, 3, 3, 1, 1]],
        device='cuda:0'),
 'Click_to_Carts_Rank-list_seq': tensor([[ 3,  8,  5,  9,  8,  4,  8,  3,  3,  3,  1,  4,  3,  3,  3, 10,  8,  8,
           9,  9]], device='cuda:0'),
 'Carts_to_Orders_Rank-list_seq': tensor([[2, 4, 1, 2, 2, 2, 2, 1, 4, 1, 1, 2, 2, 2, 4, 2, 3, 3, 2, 2]],
        device='cuda:0'),
 'Click_to_Orders_Rank-list_seq': tensor([[1, 6, 1, 5, 2, 2, 3, 1, 3, 1, 1, 1, 2, 1, 3, 4, 4, 4, 1, 1]],
        device='cuda:0'),
 'product_id-list_seq': tensor([[ 61642,  97564,  28904, 253334, 109940, 128824,  99013, 222818,  46363,
          222818,  95514,  95446, 165169, 173344,  13665, 300256, 315179, 315179,
          174603, 174603]], device='cuda:0')}

the output came out with shape of (19, number of unique item)

i can't understand why my out shape is 19 even though i put just one date

**Comment by rnyak** [comment]
@DH-HAN can you pls provide more information? is this from a your training script? or your local inference script? can you pls share your script so we can test.  

thanks.

**Comment by DH-HAN** [comment]
I handle this issue. the reason i got that kinds of shape is when i set input, i did not put aggreation option for my multiple variables. thank you for your reply!
