### ISSUE TITLE
[BUG] Merlin+pytorch container missing nvtabular

### ISSUE THREAD

**Issue by samhedin** [NVIDIA-Merlin/Transformers4Rec#606]
### Bug description

After having issues getting transformers4rec to run locally, I decided to try the docker container + vertex ai deployment
that is advertised on https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch?quick-deploy=false
which is linked to from https://github.com/NVIDIA-Merlin/Transformers4Rec#installing-transformers4rec-using-docker

### Steps/Code to reproduce bug

1. Open the link given in https://github.com/NVIDIA-Merlin/Transformers4Rec#installing-transformers4rec-using-docker and click merlin-pytorch (or click the link provided in this bug report)
2. Click "Deploy to Vertex AI"
3. Use the default setup in the vertex ai notebook creation step, and click the advised "install nvidia gpu drivers for me"
4. Open jupyter and create a new notebook
5. Paste some code from getting started > etl-with-nvtabular:
```
import os
import glob

import numpy as np
import pandas as pd

import nvtabular as nvt
from nvtabular.ops import *
from merlin.schema.tags import Tags
```
Crashes with `ModuleNotFoundError: No module named 'nvtabular'`

### Expected behavior

All imports should work

### Environment details
- Transformers4Rec version: 
- Platform:
- Python version:
- Huggingface Transformers version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

### Additional context

This issue has been one of the issues I have encountered when trying to set this up locally, which is the end goal.
However, for the sake of reproducibility I am filing this bug in the context of the docker container.

Manually creating a notebook in vertex ai and instead selecting the latest stable container,
`nvcr.io/nvidia/merlin/merlin-pytorch:22.12` results in the same error.

**Comment by rnyak** [comment]
@samhedin  thanks for reporting this. When a user pulls `nvcr.io/nvidia/merlin/merlin-pytorch:22.12` on local or cloud, they will see that it comes with all the Merlin libraries, and it works fine. Merlin is installed and used by several users on cloud.   What you report could be related to  One click Deployment on NGC feature  via `Deploy to Vertex AI ` button as you described that we do not maintain regularly.  

Are you selecting the correct kernel? if not you might get import issues on Vertex AI env..

Is your intention to install Merlin on Vertex AI or locally? what issue are you getting when you pull container from NGC on your local device?  the step you need to do  is the following:

```
docker run --gpus all  --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host nvcr.io/nvidia/merlin/merlin-pytorch:22.12 /bin/bash

cd /transformers4rec

# launch jupyter lab
jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''
``` 

thanks.

**Comment by samhedin** [comment]
It was me selecting the wrong kernel - I'm not used to jupyter notebooks.
Thank you!
