### ISSUE TITLE
How to see Affinity/score for each recommendations ?

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/Transformers4Rec#607]
# ❓ Questions & Help
I would like to see Affinity score for each recommendations after predictions ?. how can i view that in a tabular form ?

**Comment by DilipKumar3** [comment]
@rnyak  Im trying to build sequential model on my synthetic data using transformer4rec. so im trying to build an end-end model.

post the above question im trying get to know how to map the recommendations  back to original categorical values. ? session_id back to its original catgrorical values. ?

**Comment by rnyak** [comment]
For the original item_id and encoded item_id mappings you can use the `unique_item_id` parquet files in the `categories` folder that is automatically generated when you run NVT workflow.fit(...)

Please see this ticket for an example: https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/359. you can read the discussions there.

 basically if you do that
```
category_item_id =  cudf.read_parquet('/workspace/kdd/categories/unique.item_id.parquet').reset_index().rename(columns={"index": "encoded_item_id"})
```
you will get your encoded item_id column and original ids in the same cudf dataframe. then you should just do the mapping via a simple pandas or cudf function you can write.

Btw, are you using `start_index=1` in the categorify? if yes, then just shift the index column +1 in the `category_item_id`. column. If no, you can use `category_item_id` as it is.

**Comment by DilipKumar3** [comment]
Thanks for the code @rnyak 

![image](https://user-images.githubusercontent.com/48671630/216043340-6df0a767-9983-45e0-affd-66f8cba32540.png)
This is the Dataframe that im passing to the prediction. which has **13860** session(in my case customer_id)

the **prediction.predictions**  has array of length **13856**. why is this difference (passing this after trimming the users with 1 interactions) ?
when im checking the unique values of **label** in **prediction** it's only 3308 . why it does not match with 13856 ? 
based on my understanding, each record in prediction.predictions belongs to one sessions(my case customer_id). 

please correct me if my understanding is wrong.

**Comment by rnyak** [comment]
you are not going to generate predictions based on number of sessions, the predictions are generated based on your `unique item_id` in your `item_id` column in your custom train dataset. so in your raw train set, what is the number of unique item is you have? and what you see in your schema.pbtxt file?

predictions is a 2-dimentional array. first dimension shows the number of rows in your test set that you are doing predictions on, and second dimension shows your unique item catalog +1 .  For a given session (meaning each row in your transformed test set) you are getting scores for the number of unique items in your train set +1 . 

>when im checking the unique values of label in prediction it's only 3308 .
not sure I understand.  what do you mean label? can you pls explain?

**Comment by rnyak** [comment]
@DilipKumar3 I am closing this ticket due to low activity. if you have further question, please reopen the ticket.
