### ISSUE TITLE
[QST] Use HTTP instead of GRPC for inference

### ISSUE THREAD

**Issue by samhedin** [NVIDIA-Merlin/Transformers4Rec#613]
# ❓ Questions & Help
Related issue, but separate enough that I figured I should split them up: https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/612

I want to send prediction requests with HTTP instead of GRPC for deployment to Vertex AI.
(Apparently it is possible to use GRPC on Vertex AI, but the support is [experimental and undocumented](https://stackoverflow.com/questions/73612214/vertex-ai-model-serving-grpc-access-code-pointers-samples))

The end of [02-end-to-end-session-based-with-Yoochoose-PyT](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb) shows how to make requests with grpc:

```
with grpcclient.InferenceServerClient("localhost:8001") as client:
    response = client.infer(MODEL_NAME_NVT, inputs)
    print(col, ':\n', response.as_numpy(col))
```

I optimistically/naively changed this to
```
with tritonhttpclient.InferenceServerClient("localhost:8000") as client:
    response = client.infer(MODEL_NAME_NVT, inputs)
    print(col, ':\n', response.as_numpy(col))
```
which resulted in the error
```
Traceback (most recent call last):
 [...]
    response = client.infer(MODEL_NAME_NVT, inputs)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1437, in infer
    request_body, json_size = _get_inference_request(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 112, in _get_inference_request
    request_body = json.dumps(infer_request)
TypeError: name: "item-id"
datatype: "BYTES"
shape: 7
shape: 1
 is not JSON serializable
```
Item-id is a string in the raw data.
Any advice on either getting the HTTP requests all the way?

**Comment by rnyak** [comment]
@samhedin I will see if I can find an answer for this question. what's the main motivation for you of using HTTP?

**Comment by samhedin** [comment]
> @samhedin I will see if I can find an answer for this question. what's the main motivation for you of using HTTP?

Thank you! HTTP seems to be the preferred way if you look here https://cloud.google.com/vertex-ai/docs/predictions/using-nvidia-triton
Note the section on running the model locally https://cloud.google.com/vertex-ai/docs/predictions/using-nvidia-triton#run_the_container_locally_optional

**Comment by samhedin** [comment]
> @samhedin I will see if I can find an answer for this question. what's the main motivation for you of using HTTP?

It seems like all that was needed to get HTTP working was to also change grpccclient to httpclient in the line
```
inputs = nvt_triton.convert_df_to_triton_input(
    filtered_batch.columns, filtered_batch, grpccclient.InferInput
)
```

**Comment by samhedin** [comment]
... However, now it's a matter of getting online requests when it's deployed. Need to create an instances.json
https://cloud.google.com/vertex-ai/docs/predictions/using-nvidia-triton#getting_online_predictions_from_the_deployed_model
Looking into it

**Comment by rnyak** [comment]
@samhedin glad that you solved it.
