### ISSUE TITLE
[BUG] pip install tranaformers4rec has a mistake in the code 

### ISSUE THREAD

**Issue by AresDan** [NVIDIA-Merlin/Transformers4Rec#655]
### Bug description
When I use _pip install tranaformer4rec[...]_ the library is outdated, and the function _tr.TabularSequenceFeature.from_shcema_ shows an error  **'Schema' object has no attribute 'copy'**. You have already changed it in github, but not inside pip library. Could you fix it, as it's impossible to run anything? 

> 

### Steps/Code to reproduce bug
1. pip install tranaformers4rec[pytorch, nvtabular, data loader] 
2. Follow the example notebook and you will have problems with **from_schema** function. 

### Expected behavior
It should be no problems 

### Environment details
Doesn't matter, I tried on different systems and it's all the same. 
Transformers4rec version is 0.1.16

### Additional context
None

**Comment by rnyak** [comment]
@AresDan can you tell us more about your env? 
- how did you install cudf and dask_cudf?  you need these two libs to be able to run Merlin libs.
- are you cloning the TF4Rec repo from the main branch?

**Comment by AresDan** [comment]
> @AresDan can you tell us more about your env?
> 
> * how did you install cudf and dask_cudf?  you need these two libs to be able to run Merlin libs.
> * did you also install  merlin-core? https://pypi.org/project/merlin-core/
> * are you cloning the TF4Rec repo from the main branch?

I am installing them using the command from official website "conda create -n transformer_tmp -c rapidsai -c conda-forge -c nvidia  cudf=23.02 python=3.10 cudatoolkit=11.8"
So the environment is clean, and then I am installing transformer using pip command, as using conda command gives me __glibc error.
I have tried to install tranaformers4rec on Nvidia course notebook, where cudf is already installed, and I face there exactly the same problem. Old versions have the same problem as well.

And it's not about the version even, just in the code there is "schema.copy()" in "transformers4rec/torch/tabular/base.py" inside "from_schema" function. Even if you try to run inside the main program "train.schema.copy()" it will show the same error, as schema doesn't have this function. Unfortunately, pip version still uses copy() and not deepcopy() function

**Comment by rnyak** [comment]
@AresDan pip versions do not match with the latest main branches (dev branch), since pip versions are comply with the latest stable version. our latest stable version is 23.02. may be you can clone the 23.02 branch of transformers4rec lib and run the notebooks again?

besides, are you not able to use docker image? you can do `docker pull nvcr.io/nvidia/merlin/merlin-pytorch:23.02` which comes with all the libs installed so you can just start executing the nbs.

**Comment by oliverholworthy** [comment]
If you're accesing the notebooks from a git clone of the repository. Make sure you checkout the tag that corresponds to the latest release. in this case v23.02.00 (e.g. `git checkout v23.02.00`)

This version of the getting started notebook was tested alongside the version of the code availablle in the PyPI package `23.2.0`: 

https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/v23.02.00/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb

This uses a different type of Schema that was designed to work with the versions of Transformers4Rec released so far. We're working on adding support for the merlin.core Schema which is what is now being referenced in the development branch (`main`).

**Comment by oliverholworthy** [comment]
> Could you fix these notebooks in the main branch?

The main branch is currently used as the development branch of the project where we make changes to code and notebooks to reflect enhancements to the API. In the upcoming release, the new version of Transformers4Rec will support the Merlin Core Schema in addition to the one from merlin_standard_lib. We are in the process of deprecating merlin_standard_lib and replacing the use of it with the Merlin Core Schema. We are maintining backwards compatibility in the next release, however, support for the merlin_standard_lib schema will eventually be dropped. 

The notebooks on the main branch work alongside a development environment with the merlin packages checked out in development mode. Once this turns into a release, the notebook will work from an install of the released version of the Merlin packages. We are looking into changing the default branch of our repository from main to the branch corresponding to the last release to make this less likely to happen in future for those running the example notebooks.

**Comment by rnyak** [comment]
@AresDan are you still having issue? thanks.

**Comment by SpaceLearner** [comment]
Same issue encountered when using the merlin pytorch docker image of version 23.02

**Comment by rnyak** [comment]
> Same issue encountered when using the merlin pytorch docker image of version 23.02

@SpaceLearner we recommend you to use the notebooks in the container not in the main dev branch. this will solve your issue. We do not recommend users to use main branch example notebooks that might deviate from the container version. So please use whatever comes with the container. thanks.

**Comment by AresDan** [comment]
> @AresDan are you still having issue? thanks.

No, when I switched the branch, everything worked fine
