### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'transformers4rec.utils.data_utils'

### ISSUE THREAD

**Issue by jingxie-Richard** [NVIDIA-Merlin/Transformers4Rec#662]
### Bug description
 Followed this tutorial: https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/02-ETL-with-NVTabular.ipynb, and then when executing this code block: 
              from transformers4rec.utils.data_utils import save_time_based_splits
save_time_based_splits(data=nvt.Dataset(sessions_gdf),
                       output_dir= OUTPUT_FOLDER,
                       partition_col=PARTITION_COL,
                       timestamp_col='user_session', 
                      )

I faced ModuleNotFoundError: No module named 'transformers4rec.utils.data_utils' error. I only found one relevant issue: https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/629 and tried to follow that solution. But still did not solve the problem. Now I installed the latest version: 
import transformers4rec

print(transformers4rec.__version__)

version: 23.02.00

### Steps/Code to reproduce bug

1. 
2. 
3. 

### Environment details
- Transformers4Rec version:  23.02.00
- Platform: Databricks GPU cluster (12.2 LTS ML (includes Apache Spark 3.3.2, GPU, Scala 2.12))
- Python version: Python 3.9.5
- Huggingface Transformers version:
- PyTorch version (GPU?): 1.13.1+cu117 (GPU) 
- Tensorflow version (GPU?):

**Comment by rnyak** [comment]
@jingxie-Richard hello. this is not a bug. this happens bcs you install Merlin's latest stable versions but you use the notebooks from the main branch. How do you install Merlin libraries? via pip? or do you use docker image?

if you install via pip, I recommend you to start from a clean env and then install Merlin libs again. Do not install Merlin from main (dev) branch and do not use the notebooks from main branch.  Please use the notebooks from `release-23.02` branch.

 then if you do `from transformers4rec.data.preprocessing import save_time_based_splits` it should work.

**Comment by jingxie-Richard** [comment]
@rnyak thank you very much for your reply! 
I installed Merlin libraries via pip since my working environment is Databricks GPU cluster which does not support the Merlin docker image. I did start from a clean env when I faced the above issue. 
I will use the notebooks from release-23.02 branch and try it again. If I have any problems, I will update it.

**Comment by jingxie-Richard** [comment]
@rnyak I just tested the notebooks from release-23.02 branch and they works. Thanks again!
