### ISSUE TITLE
[Task] Add topK layer in model to return topK items at inference step

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#668]
### Description

At inference, we generate scores for all the items in the catalog per session. If we add a topK layer, we will be able to return topK items with the highest scores at inference step automatically.

**Comment by viswa-nvidia** [comment]
@rnyak , please review and let us know if it can happen in 23.04

**Comment by viswa-nvidia** [comment]
@rnyak please link PR and close

**Comment by rnyak** [comment]
completed via https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/678
