### ISSUE TITLE
[BUG] RuntimeError: cuDF failure : Unsupported type_id conversion to cudf

### ISSUE THREAD

**Issue by mtnt-2022** [NVIDIA-Merlin/Transformers4Rec#674]
### Bug description

RuntimeError: cuDF failure at: /opt/rapids/src/cudf/cpp/src/interop/from_arrow.cu:86: Unsupported type_id conversion to cudf

### Steps/Code to reproduce bug

1. please run the notebook at [Transformers4Rec](https://github.com/NVIDIA-Merlin/Transformers4Rec)/[examples](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples)/[getting-started-session-based](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based)/01-ETL-with-NVTabular.ipynb
2. the cell below "Feature Engineering with NVTabular" will pop this error.
3. it was caused by " dataset = nvt.Dataset(df)" 

### Environment details
- Transformers4Rec version:  23.2.0
- Platform: Debian 4.19.269-1
- Python version: 3.8.10
- Huggingface Transformers version: 4.18.0
- PyTorch version (GPU?): 2.0.0 (yes support GPU)
- Tensorflow version (GPU?):

### Additional context

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[24], line 53
     49 seq_feats_list = filtered_sessions['item_id-list', 'category-list', 'age_days-list', 'weekday_sin-list'] >>  nvt.ops.ValueCount()
     51 workflow = nvt.Workflow(filtered_sessions['session_id', 'day-first'] + seq_feats_list)
---> 53 dataset = nvt.Dataset(df)
     55 # Generate statistics for the features and export parquet files
     56 # this step will generate the schema file
     57 workflow.fit_transform(dataset).to_parquet(os.path.join(INPUT_DATA_DIR, "processed_nvt"))

File /usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py:265, in Dataset.__init__(self, path_or_source, engine, npartitions, part_size, part_mem_fraction, storage_options, dtypes, client, cpu, base_dataset, schema, **kwargs)
    259 npartitions = npartitions or 1
    260 if isinstance(path_or_source, dask.dataframe.DataFrame) or is_dataframe_object(
    261     path_or_source
    262 ):
    263     # User is passing in a <dask.dataframe|cudf|pd>.DataFrame
    264     # Use DataFrameDatasetEngine
--> 265     _path_or_source = convert_data(
    266         path_or_source, cpu=self.cpu, to_collection=True, npartitions=npartitions
    267     )
    268     # Check if this is a collection that has now moved between host <-> device
    269     moved_collection = isinstance(path_or_source, dask.dataframe.DataFrame) and (
    270         not isinstance(_path_or_source._meta, type(path_or_source._meta))
    271     )

File /usr/local/lib/python3.8/dist-packages/merlin/core/dispatch.py:603, in convert_data(x, cpu, to_collection, npartitions)
    601     _x = cudf.DataFrame.from_arrow(x)
    602 elif isinstance(x, pd.DataFrame):
--> 603     _x = cudf.DataFrame.from_pandas(x)
    604 # Output a collection if `to_collection=True`
    605 return (
    606     dask_cudf.from_cudf(_x, sort=False, npartitions=npartitions)
    607     if to_collection
    608     else _x
    609 )

File /usr/local/lib/python3.8/dist-packages/nvtx/nvtx.py:101, in annotate.__call__.<locals>.inner(*args, **kwargs)
     98 @wraps(func)
     99 def inner(*args, **kwargs):
    100     libnvtx_push_range(self.attributes, self.domain.handle)
--> 101     result = func(*args, **kwargs)
    102     libnvtx_pop_range(self.domain.handle)
    103     return result

File /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py:4819, in DataFrame.from_pandas(cls, dataframe, nan_as_null)
   4815 for col_name, col_value in dataframe.items():
   4816     # necessary because multi-index can return multiple
   4817     # columns for a single key
   4818     if len(col_value.shape) == 1:
-> 4819         data[col_name] = column.as_column(
   4820             col_value.array, nan_as_null=nan_as_null
   4821         )
   4822     else:
   4823         vals = col_value.values.T

File /usr/local/lib/python3.8/dist-packages/cudf/core/column/column.py:1987, in as_column(arbitrary, nan_as_null, dtype, length)
   1985     data = as_column(pa.Array.from_pandas(arbitrary), dtype=arb_dtype)
   1986 else:
-> 1987     data = as_column(
   1988         pa.array(
   1989             arbitrary,
   1990             from_pandas=True if nan_as_null is None else nan_as_null,
   1991         ),
   1992         nan_as_null=nan_as_null,
   1993     )
   1994 if dtype is not None:
   1995     data = data.astype(dtype)

File /usr/local/lib/python3.8/dist-packages/cudf/core/column/column.py:1769, in as_column(arbitrary, nan_as_null, dtype, length)
   1763 if isinstance(arbitrary, pa.lib.HalfFloatArray):
   1764     raise NotImplementedError(
   1765         "Type casting from `float16` to `float32` is not "
   1766         "yet supported in pyarrow, see: "
   1767         "https://issues.apache.org/jira/browse/ARROW-3802"
   1768     )
-> 1769 col = ColumnBase.from_arrow(arbitrary)
   1771 if isinstance(arbitrary, pa.NullArray):
   1772     new_dtype = cudf.dtype(arbitrary.type.to_pandas_dtype())

File /usr/local/lib/python3.8/dist-packages/cudf/core/column/column.py:296, in ColumnBase.from_arrow(cls, array)
    291 elif isinstance(
    292     array.type, pd.core.arrays._arrow_utils.ArrowIntervalType
    293 ):
    294     return cudf.core.column.IntervalColumn.from_arrow(array)
--> 296 result = libcudf.interop.from_arrow(data)[0]
    298 return result._with_type_metadata(cudf_dtype_from_pa_type(array.type))

File interop.pyx:150, in cudf._lib.interop.from_arrow()

RuntimeError: cuDF failure at: /opt/rapids/src/cudf/cpp/src/interop/from_arrow.cu:86: Unsupported type_id conversion to cudf

**Comment by rnyak** [comment]
@mtnt-2022  we need to know how did you install Merlin, cudf and dask_cudf first? 
- are you using `merlin-pytorch:23.02` docker image? if not did you install Merlin libs, cudf and dask_cudf with `pip`? if yes how?
- what's your GPU specs?
- where do you run this notebook? on a WS or on a cloud instance? if the latter which one?
thanks.

**Comment by mtnt-2022** [comment]
@rnyak 

Q: are you using merlin-pytorch:23.02 docker image? if not did you install Merlin libs, cudf and dask_cudf with pip? if yes how?
A: yes, nvcr.io/nvidia/merlin/merlin-pytorch:23.02. All cudf libs were installed by GCP by default.

Q: what's your GPU specs?  
A: NVIDIA T4

Q: where do you run this notebook? on a WS or on a cloud instance? if the latter which one?
A: GCP Vertex AI workbench virtual machine.   

thanks.

**Comment by rnyak** [comment]
@mtnt-2022 
>yes, nvcr.io/nvidia/merlin/merlin-pytorch:23.02. All cudf libs were installed by GCP by default.
what's that mean all cudf libs installed by GCP by default? all cudfs should be installed in the docker image, you should not install any cudf or dask_cudf if you are using merlin docker image.

can you please share your `cudf` and `dask_cudf` and all merlin lib versions?  this is our support [matrix](https://nvidia-merlin.github.io/Merlin/main/support_matrix/support_matrix_merlin_pytorch.html), you can check the lib versions that you need to have in 23.02 pytorch image.

**Comment by mtnt-2022** [comment]
@rnyak 
please see the libs that I have: 

cudf   :                  22.8.0a0+304.g6ca81bbc78.dirty
dask-cudf  :         22.8.0a0+304.g6ca81bbc78.dirty

CUDA Version:    11.8     
NVIDIA-SMI        510.47.03    
Driver Version:  510.47.03 

merlin                                1.9.1
merlin-core                           0.5.0
merlin-dataloader                     0.0.3
merlin-models                         23.2.0
merlin-systems                        23.2.0

nvidia-cublas-cu11                    11.10.3.66
nvidia-cuda-cupti-cu11                11.7.101
nvidia-cuda-nvrtc-cu11                11.7.99
nvidia-cuda-runtime-cu11              11.7.99
nvidia-cudnn-cu11                     8.5.0.96
nvidia-cufft-cu11                     10.9.0.58
nvidia-curand-cu11                    10.2.10.91
nvidia-cusolver-cu11                  11.4.0.1
nvidia-cusparse-cu11                  11.7.4.91
nvidia-nccl-cu11                      2.14.3
nvidia-nvtx-cu11                      11.7.91
nvidia-pyindex                        1.0.9
nvtabular                             23.2.0

GPU :   Tesla T4 
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

triton                                2.0.0
tritonclient                          2.32.0


Ubuntu          20.04.5 LTS
rmm               22.8.0a0+62.gf6bf047.dirty
torch                                 2.0.0

**Comment by rnyak** [comment]
@mtnt-2022 are you running the `[Transformers4Rec](https://github.com/NVIDIA-Merlin/Transformers4Rec)/[examples](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples)/[getting-started-session-based](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based)/01-ETL-with-NVTabular.ipynb` as it is or with your custom dataset?

**Comment by mtnt-2022** [comment]
@rnyak , yes,  I am running this nb as it is.

**Comment by rnyak** [comment]
> @rnyak , yes, I am running this nb as it is.

thanks. any chance you can get a GPU instance where the driver is > =  515.65.01 ?

**Comment by mtnt-2022** [comment]
@rnyak , 
Currently, we are using NVIDIA T4 GPU. The driver may be different for different GPU instance ?  Please let me know how to update the driver version ? 

Also, based on https://rapids.ai/pip.html, 

CUDA & NVIDIA Drivers: One of the following supported versions:

 [CUDA 11.2](https://developer.nvidia.com/cuda-11.2.0-download-archive) with Driver 460.27.03 or newer
 [CUDA 11.4](https://developer.nvidia.com/cuda-11-4-0-download-archive) with Driver 470.42.01 or newer
 [CUDA 11.5](https://developer.nvidia.com/cuda-11-5-0-download-archive) with Driver 495.29.05 or newer
 [CUDA 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive) with Driver 520.61.05 or newer

Because our CUDA is 11.8, so the Driver must be >= 520.61.05 ? Otherwise, RAPIDS (including cudf) will not work correctly on GCP ?  thanks

**Comment by mtnt-2022** [comment]
@rnyak , I have tried other GPU instances: NVIDIA Tesla P4, Tesla V100 and got the same error. They all have the GPU driver:
   NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.8 

I got the same error.

**Comment by rnyak** [comment]
@mtnt-2022 can you please test if you are able to do `import cudf` and then test if you can create a cudf df, and then run a simple nvt workflow 

```
import cudf
import nvtabular as nvt
df = cudf.DataFrame({'a_user_id': ["User_A","User_E","User_B","User_C","User_A","User_B","User_B","User_C","User_B","User_A"], 
                    'media':[3, 3, 12, 17, 3, 1, 1, 0, 1, 12], 'language': ['en', 'en', 'spn', 'fr', 'spn', 'en', 'fr', 'ch', 'ch', 'en']})

print(df)

dataset = nvt.Dataset(df)
cats= (['a_user_id','media', 'language']) >> nvt.ops.Categorify()

workflow = nvt.Workflow(cats)
workflow.fit(dataset)
new_gdf = workflow.transform(dataset).to_ddf().compute()
new_gdf.head()
```
we have some instructions for you to start a GCP instance and install Merlin libs there.

https://github.com/MarkMoTrin/merlin-install-gcp/blob/main/README.md

you can follow the steps in the readme above but you need to pull the correct container:

```
sudo docker pull nvcr.io/nvidia/merlin/merlin-pytorch:23.04
sudo docker run --rm -it --runtime=nvidia --gpus all -p 8888:8888 -p 8797:8787 -p 8796:8786 nvcr.io/nvidia/merlin/merlin-pytorch:23.04 /bin/bash
```

**Comment by rnyak** [comment]
@mtnt-2022 I am closing this ticket due to low activity. please reopen if you have further questions.
